stages:
  - stage: 'code_check'
    displayName: 'code check (style/quality)'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'style_terraform_fmt'
        displayName: 'style:terraform-fmt'
        steps:
          # $(Scripts.Directory) was already defined in the line below
          - template: '../../abstracts/terra-terraform1.9.3.yaml'

          - script: terraform fmt -check -recursive
            displayName: 'Run Terraform format check'

          - script: ./terragrunt hclfmt --terragrunt-check **/*.hcl
            displayName: 'Run Terragrunt HCL format check'

          - script: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            displayName: 'Install TFLint'

          - script: tflint --chdir . --recursive
            displayName: 'Run TFLint'
