parameters:
  - name: 'GRADLE_TEST_TASKS'
    type: 'object'
    default: []

jobs:
  - template: '../../abstracts/code-check.yaml'
    parameters:
      GRADLE_TEST_TASKS: ${{ parameters.GRADLE_TEST_TASKS }}

  - job: 'style_ktlint'
    displayName: 'style:ktlint'
    steps:
      - template: '../../abstracts/gradle.yaml'

      - task: 'Gradle@3'
        inputs:
          tasks: 'ktlintCheck'
          ${{ if gt(length(parameters.GRADLE_TEST_TASKS), 0) }}:
            options: "-x ${{ join(' -x ', parameters.GRADLE_TEST_TASKS) }}"
          publishJUnitResults: false
        displayName: 'ktlint'
