inputs:
  github_token:
    type: 'string'
    required: true
  source_tag:
    type: 'string'
    required: true
    description: 'Source tag to pull (e.g., latest)'
  target_tag:
    type: 'string'
    required: true
    description: 'Target tag to push (e.g., v1.0.0)'
  registry:
    type: 'string'
    required: false
    default: 'ghcr.io'
    description: 'Container registry URL'

runs:
  using: 'composite'
  steps:
    - name: 'Login to Registry'
      uses: 'docker/login-action@v3'
      with:
        registry: '${{ inputs.registry }}'
        username: '${{ github.actor }}'
        password: '${{ inputs.github_token }}'

    - name: 'Pull source image'
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.registry }}/${{ github.repository }}"
        SOURCE_TAG="${{ inputs.source_tag }}"
        
        echo "Pulling ${IMAGE_NAME}:${SOURCE_TAG}..."
        docker pull "${IMAGE_NAME}:${SOURCE_TAG}"
        
        # Verify the image was pulled successfully
        if ! docker image inspect "${IMAGE_NAME}:${SOURCE_TAG}" > /dev/null 2>&1; then
          echo "Error: Failed to pull ${IMAGE_NAME}:${SOURCE_TAG}"
          echo "Please ensure the source image exists before creating a release tag."
          exit 1
        fi
        
        # Get and display the image digest
        DIGEST=$(docker image inspect "${IMAGE_NAME}:${SOURCE_TAG}" --format='{{index .RepoDigests 0}}')
        echo "Source image digest: ${DIGEST}"
        echo "IMAGE_DIGEST=${DIGEST}" >> $GITHUB_ENV

    - name: 'Tag with release version'
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.registry }}/${{ github.repository }}"
        SOURCE_TAG="${{ inputs.source_tag }}"
        TARGET_TAG="${{ inputs.target_tag }}"
        
        echo "Tagging ${IMAGE_NAME}:${SOURCE_TAG} as ${IMAGE_NAME}:${TARGET_TAG}..."
        docker tag "${IMAGE_NAME}:${SOURCE_TAG}" "${IMAGE_NAME}:${TARGET_TAG}"

    - name: 'Push release tag'
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.registry }}/${{ github.repository }}"
        TARGET_TAG="${{ inputs.target_tag }}"
        
        echo "Pushing ${IMAGE_NAME}:${TARGET_TAG}..."
        docker push "${IMAGE_NAME}:${TARGET_TAG}"
        
        # Verify the pushed image has the same digest
        PUSHED_DIGEST=$(docker image inspect "${IMAGE_NAME}:${TARGET_TAG}" --format='{{index .RepoDigests 0}}')
        echo "Pushed image digest: ${PUSHED_DIGEST}"
        
        if [ "$IMAGE_DIGEST" != "$PUSHED_DIGEST" ]; then
          echo "Warning: Digest mismatch detected"
          echo "  Source: $IMAGE_DIGEST"
          echo "  Pushed: $PUSHED_DIGEST"
        else
          echo "✓ Successfully retagged image with matching digest"
        fi
