stages:
  - stage: 'security'
    displayName: 'security (sca/sast)'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: '../../../global/stages/20-security/docker.yaml'
        parameters:
          SEMGREP_LANGUAGE: 'javascript'

      - template: '../../../global/stages/20-security/codeql.yaml'
        parameters:
          CODEQL_LANGUAGE: 'javascript'

      - template: '../../../global/stages/20-security/hadolint.yaml'

      - template: '../../../global/stages/20-security/trivy.yaml'

      - template: '../../../global/stages/20-security/trivy-sca.yaml'

      - job: 'sca_yarn_audit'
        displayName: 'sca:yarn-audit'
        steps:
          - template: '../../abstracts/corepack-node20.18.3-no-cache.yaml'
          - script: yarn npm audit --recursive --severity high
            displayName: 'Run yarn npm audit'
        continueOnError: true
