stages:
  - stage: 'code_check'
    displayName: 'code check (style/quality)'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'style_golangci_lint'
        displayName: 'style:golangci-lint'
        variables:
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          - task: 'Cache@2'
            inputs:
              key: "$(Agent.JobName)|$(Agent.OS)|go.sum"
              path: "$(GOPATH)"
            displayName: 'Cache for Go modules'
            continueOnError: true

          - template: '../../../global/abstracts/scripts-repo.yaml'
          - script: $(Scripts.Directory)/global/scripts/golang/init/run.sh
            displayName: 'Load Custom Configuration'

          - task: 'GoTool@0'
            inputs:
              version: '1.23.4'
              architecture: 'amd64'
              goArguments: 'mod tidy'

          # for golangci-lint config merging
          - script: |
              sudo apt-get update && \
              sudo apt-get install -y python3 python3-yaml
            displayName: 'Install dependencies'

          - script: $(Scripts.Directory)/global/scripts/golangci-lint/run.sh
            displayName: 'Run GolangCI-Lint'
