include:
  - local: '/gitlab/global/abstracts/default-image.yaml'
  - local: '/gitlab/java/stages/10-code-check/gradle-application.yaml'
  - local: '/gitlab/java/stages/20-security/gradle-application.yaml'
  - local: '/gitlab/java/stages/30-tests/gradle-application.yaml'
  - local: '/gitlab/java/stages/35-management/gradle-application.yaml'
  - local: '/gitlab/global/stages/40-delivery/docker.yaml'
  - local: '/gitlab/global/stages/40-delivery/release.yaml'
  #- local: '/gitlab/global/stages/50-deployment/k8s.yaml'

stages:
  - 'code check (style/quality)'
  - 'security (sca/sast)'
  - 'tests'
  - 'management'
  - 'delivery'
  - 'deployment'
