include:
  - local: '/global/abstracts/default-image.yaml'
  - local: '/java/stages/10-code-check/gradle-library.yaml'
  - local: '/java/stages/20-security/gradle-library.yaml'
  - local: '/java/stages/30-tests/gradle-library.yaml'
  - local: '/java/stages/35-management/gradle-library.yaml'
  - local: '/java/stages/40-delivery/gradle-library.yaml'
  - local: '/global/stages/40-delivery/release.yaml'

stages:
  - 'code check (style/quality)'
  - 'security (sca/sast)'
  - 'tests'
  - 'management'
  - 'delivery'
