runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v6'

    - name: 'Setup Go'
      uses: 'actions/setup-go@v6'
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - uses: 'rios0rios0/pipelines/github/global/abstracts/scripts-repo@main'

    - run: $SCRIPTS_DIR/global/scripts/languages/golang/cross-compile/run.sh
      shell: 'bash'
