stages:
  - stage: 'tests'
    displayName: 'tests'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        steps:
          - template: '../../abstracts/pdm-python3.13.yaml'
          - script: |
              pdm run test
            displayName: 'Run Tests'

        continueOnError: false
