stages:
  - stage: 'management'
    displayName: 'management'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: '../../../global/stages/35-management/sonarqube.yaml'

      - job: 'report_dependency_track'
        displayName: 'report:dependency-track'
        continueOnError: true
        # TODO: this is being repeated all over the place
        variables:
          PREFIX: ''
          REPORT_PATH: 'build/reports'
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          - task: 'Cache@2'
            inputs:
              key: "$(Agent.JobName)|$(Agent.OS)|go.sum"
              path: "$(GOPATH)"
            displayName: 'Cache for Go modules'
            continueOnError: true

          - template: '../../../global/abstracts/scripts-repo.yaml'
          - script: $(Scripts.Directory)/global/scripts/golang/init/run.sh
            displayName: 'Load Custom Configuration'

          - task: 'GoTool@0'
            inputs:
              version: '1.23.4'
              architecture: 'amd64'
              goArguments: 'mod tidy'

          - script: $(Scripts.Directory)/global/scripts/golang/cyclonedx/run.sh
          - script: $(Scripts.Directory)/global/scripts/dependency-track/run.sh
