include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/fix/test/gitlab/java/abstracts/gradle-application.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/fix/test/gitlab/java/stages/20-security/gradle.yaml'

variables:
  PREFIX: ''

.dependency-check:
  extends: '.gradle-application'
  cache:
    paths:
      - '.gradle'
      - '.gradle-home/caches'
      - '.gradle-home/notifications'
      - '.owasp'
      - 'build'
      - 'buildSrc/.gradle'
      - 'buildSrc/build'
