version = 0.1

[default]
[default.global.parameters]
stack_name = "my-go-lambda-stack"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
