on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v6'

    - name: 'Get Scripts'
      uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@main'

    - name: 'Execute'
      shell: 'bash'
      run: $SCRIPTS_DIR/global/scripts/gitleaks/run.sh

    - name: 'Upload Report'
      uses: 'actions/upload-artifact@v6'
      with:
        name: 'gitleaks'
        path: 'build/reports/gitleaks.json'
        if-no-files-found: 'error'
        overwrite: 'true'
        retention-days: 10
      if: always()
