#!/usr/bin/env bash
set -e

# Test script for the shared variable-declaration generator.
#
# Exercises gen_shared_variables.py against synthetic Terragrunt layouts. The
# cases concentrate on the two classes of bug this tool can have, because both
# are quiet:
#
#   1. PARSING. The tool decides what a stack needs by scanning for `var.<name>`
#      and what it already has by scanning for `variable "<name>"`. Both scans
#      are text-level, so a comment or a string literal can fool them -- and the
#      symptom is a MISSING or SPURIOUS declaration several steps away from the
#      cause. Two real bugs found this way are pinned here as regressions: the
#      `//` inside `"https://..."` swallowing an interpolation, and `<<-` heredoc
#      bodies emitted still indented (valid Terraform, but invisible to any
#      scanner anchored at column 0 -- which is how the sibling order-check
#      collects declared names).
#
#   2. DESTRUCTION. Committed generated code is only safe if a rerun cannot
#      quietly disagree with what is checked in, and if the generator never
#      overwrites something a human wrote. The sibling tftest-gen learned the
#      second one the expensive way.

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GEN="$SCRIPTS_DIR/global/scripts/languages/terraform/var-catalog/gen_shared_variables.py"
RUN_SH="$SCRIPTS_DIR/global/scripts/languages/terraform/var-catalog/run.sh"
TEST_DIR="$(mktemp -d)"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0

assert_true() {
  local description="$1"
  local condition="$2"
  if eval "$condition"; then
    echo -e "${GREEN}  PASS: $description${NC}"
    TESTS_PASSED=$((TESTS_PASSED + 1))
  else
    echo -e "${RED}  FAIL: $description${NC}"
    TESTS_FAILED=$((TESTS_FAILED + 1))
  fi
}

cleanup() { rm -rf "$TEST_DIR"; }
trap cleanup EXIT

gen() { python3 "$GEN" "$@"; }

# new_repo <name> -- a synthetic repo with a two-entry catalog, echoing its path.
new_repo() {
  local repo="$TEST_DIR/$1"
  mkdir -p "$repo/stacks"
  cat > "$repo/.terraform-var-catalog.hcl" <<'EOF'
locals {
  declarations = {
    environment = <<-EOT
      variable "environment" {
        type        = string
        description = "The environment name."
      }
    EOT

    tags = <<-EOT
      variable "tags" {
        type        = map(string)
        description = "Tags applied to every resource."
      }
    EOT
  }
}
EOF
  echo "$repo"
}

echo "=== var-catalog generator ==="

# --- generates only what a stack references ---------------------------------
REPO="$(new_repo only-what-is-used)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
gen --repo-dir "$REPO" >/dev/null
OUT="$REPO/stacks/01_alpha/variables-shared.tf"
assert_true "generates a file for a stack that references a catalogued variable" "[ -f '$OUT' ]"
assert_true "declares the referenced variable" "grep -q 'variable \"environment\"' '$OUT'"
assert_true "omits a catalogued variable the stack never references" "! grep -q 'variable \"tags\"' '$OUT'"
assert_true "emits declarations at column 0, not indented" "grep -q '^variable \"environment\"' '$OUT'"
assert_true "carries the AUTOGENERATED marker on line 1" "head -1 '$OUT' | grep -q 'AUTOGENERATED by var-catalog'"

# --- a `//` inside a string is not a comment (regression) --------------------
REPO="$(new_repo url-not-comment)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
locals {
  api = "https://api.example.${var.environment}/catalog"
}
EOF
gen --repo-dir "$REPO" >/dev/null
assert_true "sees var.<name> after a // inside a string literal" \
  "grep -q 'variable \"environment\"' '$REPO/stacks/01_alpha/variables-shared.tf'"

# --- a `/* */` inside a string is not a comment either -----------------------
REPO="$(new_repo block-comment-in-string)"
mkdir -p "$REPO/stacks/01_alpha"
# The reference must sit INSIDE the fake comment span, or a regex pre-pass
# deletes the delimiters and leaves the reference behind -- passing for the
# wrong reason. This fixture is the one that actually fails without the
# string-aware scan.
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
locals {
  pattern = "/* ${var.environment} */"
}
EOF
gen --repo-dir "$REPO" >/dev/null
assert_true "sees var.<name> after a /* */ inside a string literal" \
  "grep -q 'variable \"environment\"' '$REPO/stacks/01_alpha/variables-shared.tf'"

# --- a real comment does NOT resurrect a declaration -------------------------
REPO="$(new_repo comment-does-not-count)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
# this stack used to read var.tags before the refactor
/* and this block comment mentions var.tags too */
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
gen --repo-dir "$REPO" >/dev/null
assert_true "a commented-out var.<name> does not resurrect its declaration" \
  "! grep -q 'variable \"tags\"' '$REPO/stacks/01_alpha/variables-shared.tf'"

# --- a stack whose entry file is not main.tf is still discovered -------------
REPO="$(new_repo entry-file-not-main)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main-cluster.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
gen --repo-dir "$REPO" >/dev/null
assert_true "discovers a root module whose entry file is not called main.tf" \
  "[ -f '$REPO/stacks/01_alpha/variables-shared.tf' ]"

# --- never overwrites a hand-written declaration -----------------------------
REPO="$(new_repo preserves-handwritten)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
cat > "$REPO/stacks/01_alpha/variables.tf" <<'EOF'
variable "environment" {
  type        = string
  description = "This stack's own wording, which says something the canonical body does not."
}
EOF
PRESERVE_OUT="$(gen --repo-dir "$REPO")"
assert_true "reports a hand-written declaration as PRESERVED" \
  "echo '$PRESERVE_OUT' | grep -q 'PRESERVED'"
assert_true "leaves the hand-written body untouched" \
  "grep -q 'says something the canonical body does not' '$REPO/stacks/01_alpha/variables.tf'"
assert_true "does not emit a duplicate declaration (a hard Terraform error)" \
  "[ ! -f '$REPO/stacks/01_alpha/variables-shared.tf' ]"

# --- --check is a gate, and writes nothing ----------------------------------
REPO="$(new_repo check-mode)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
set +e
gen --repo-dir "$REPO" --check >/dev/null 2>&1
CHECK_MISSING_RC=$?
set -e
assert_true "--check fails when the generated file is missing" "[ $CHECK_MISSING_RC -ne 0 ]"
assert_true "--check wrote nothing" "[ ! -f '$REPO/stacks/01_alpha/variables-shared.tf' ]"

gen --repo-dir "$REPO" >/dev/null
set +e
gen --repo-dir "$REPO" --check >/dev/null 2>&1
CHECK_CLEAN_RC=$?
set -e
assert_true "--check passes once the output is committed" "[ $CHECK_CLEAN_RC -eq 0 ]"

echo 'variable "hand_edited" { type = string }' >> "$REPO/stacks/01_alpha/variables-shared.tf"
set +e
gen --repo-dir "$REPO" --check >/dev/null 2>&1
CHECK_DRIFT_RC=$?
set -e
assert_true "--check fails when a generated file was hand-edited" "[ $CHECK_DRIFT_RC -ne 0 ]"

# --- --report never writes and never fails ----------------------------------
REPO="$(new_repo report-mode)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
set +e
gen --repo-dir "$REPO" --report >/dev/null 2>&1
REPORT_RC=$?
set -e
assert_true "--report exits 0 even with pending changes" "[ $REPORT_RC -eq 0 ]"
assert_true "--report wrote nothing" "[ ! -f '$REPO/stacks/01_alpha/variables-shared.tf' ]"

# --- a stale generated file is removed when nothing references it any more ---
REPO="$(new_repo removes-stale)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
gen --repo-dir "$REPO" >/dev/null
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { fixed = "no variables here" }
}
EOF
gen --repo-dir "$REPO" >/dev/null
assert_true "removes a generated file once the stack references nothing" \
  "[ ! -f '$REPO/stacks/01_alpha/variables-shared.tf' ]"

# --- a repo with no catalog is a no-op, not an error ------------------------
REPO="$TEST_DIR/no-catalog"
mkdir -p "$REPO/stacks/01_alpha"
echo 'resource "null_resource" "a" {}' > "$REPO/stacks/01_alpha/main.tf"
set +e
NOCAT_OUT="$(gen --repo-dir "$REPO" 2>&1)"
NOCAT_RC=$?
set -e
assert_true "a repo with no catalog exits 0" "[ $NOCAT_RC -eq 0 ]"
assert_true "a repo with no catalog says so" "echo '$NOCAT_OUT' | grep -q 'nothing to do'"

# --- the runner wrapper is usable -------------------------------------------
REPO="$(new_repo runner)"
mkdir -p "$REPO/stacks/01_alpha"
cat > "$REPO/stacks/01_alpha/main.tf" <<'EOF'
resource "null_resource" "a" {
  triggers = { env = var.environment }
}
EOF
set +e
"$RUN_SH" --repo-dir "$REPO" >/dev/null 2>&1
RUN_RC=$?
set -e
assert_true "run.sh drives the generator" \
  "[ $RUN_RC -eq 0 ] && [ -f '$REPO/stacks/01_alpha/variables-shared.tf' ]"

echo ""
echo "Passed: $TESTS_PASSED  Failed: $TESTS_FAILED"
[ "$TESTS_FAILED" -eq 0 ]
