parameters:
  - name: 'RUN_BEFORE_DEPLOYMENT'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DEPLOYMENT'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'deployment'
    displayName: 'deployment'
    condition: and(not(failed()), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    dependsOn: 'delivery'
    variables:
      CONTAINER_IMAGE: $[stageDependencies.delivery.delivery.outputs['build.CONTAINER_IMAGE']]
    jobs:
      - job: 'deployment'
        displayName: 'deployment'
        steps:
          - script: |
              ${{ parameters.RUN_BEFORE_DELIVERY }}
            displayName: 'Run Before'

          - task: 'Kubernetes@1'
            displayName: 'Patch Deployment Using JSON Patch File'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: "$(K8S_ENDPOINT)"
              namespace: "$(K8S_NAMESPACE)"
              command: 'patch'
              arguments: >
                deployment $(K8S_DEPLOYMENT_NAME) --patch-file "$(Build.SourcesDirectory)/kubernetes/k8s-patch.json"

          - task: 'Kubernetes@1'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: "$(K8S_ENDPOINT)"
              namespace: "$(K8S_NAMESPACE)"
              command: 'rollout'
              arguments: "restart deployment/$(K8S_DEPLOYMENT_NAME)"

          - script: |
              ${{ parameters.RUN_AFTER_DELIVERY }}
            displayName: 'Run After'
