parameters:
  - name: 'RUN_BEFORE_DEPLOYMENT'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DEPLOYMENT'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'deployment'
    displayName: 'deployment'
    condition: and(not(failed()), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    dependsOn: 'delivery'
    variables:
      CONTAINER_IMAGE: $[stageDependencies.delivery.delivery.outputs['build.CONTAINER_IMAGE']]
    jobs:
      - job: 'deployment'
        displayName: 'deployment'
        steps:
          - template: 'steps/deployment.yaml'
            parameters:
              RUN_BEFORE_DEPLOYMENT: ${{ parameters.RUN_BEFORE_DEPLOYMENT }}
              RUN_AFTER_DEPLOYMENT: ${{ parameters.RUN_AFTER_DEPLOYMENT }}
