parameters:
  - name: 'GRADLE_PUBLISH_TASK'
    type: string
    default: ''
  - name: 'GRADLE_TEST_TASKS'
    type: object
    default: []
  - name: 'GRADLE_PROPERTIES'
    type: object
    default: []

stages:
  - stage: 'delivery'
    displayName: 'delivery'
    condition: and(not(failed()), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        steps:
          - template: '../../abstracts/gradle.yaml'
            parameters:
              GRADLE_PROPERTIES: ${{ parameters.GRADLE_PROPERTIES }}

          - task: 'Gradle@3'
            inputs:
              tasks: '${{ parameters.GRADLE_PUBLISH_TASK }}'
              ${{ if gt(length(parameters.GRADLE_TEST_TASKS), 0) }}:
                options: "-x ${{ join(' -x ', parameters.GRADLE_TEST_TASKS) }}"
              publishJUnitResults: false
            displayName: 'Gradle Publish'

      - template: '../../../global/stages/40-delivery/release.yaml'
