stages:
  - stage: 'management'
    displayName: 'management'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: '../../../global/stages/35-management/sonarqube.yaml'

      - job: 'report_dependency_track'
        displayName: 'report:dependency-track'
        variables:
          REPORT_PATH: 'build/reports'
        steps:
          # $(Scripts.Directory) was already defined in the line below
          - template: '../../abstracts/go1.23.4.yaml'

          - script: $(Scripts.Directory)/global/scripts/dependency-track/run.sh
        continueOnError: true
