stages:
  - stage: 'management'
    displayName: 'management'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: '../../../global/stages/35-management/sonarqube.yaml'

      - job: 'report_dependency_track'
        displayName: 'report:dependency-track'
        variables:
          REPORT_PATH: 'build/reports'
        steps:
          # TODO: see https://www.reddit.com/r/Terraform/comments/1g9go7p/what_do_you_use_to_generate_sbom_for_terraform/
          - script: echo "$(date "+%Y-%m-%d %H:%M:%S") - Missing Cyclonedx for Terraform..."

          - template: '../../../global/abstracts/scripts-repo.yaml'
          - script: $(Scripts.Directory)/global/scripts/dependency-track/run.sh
        continueOnError: true
