stages:
  - stage: 'management'
    displayName: 'management'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'report_sonarqube'
        displayName: 'report:sonarqube'
        variables:
          SONAR_USER_HOME: "$(Build.SourcesDirectory)/.sonar"
        steps:
          # TODO: duplicated code 3 times, 2 here and another at clone-and-move-opensearch-dashboards.yaml
          - task: 'UseNode@1'
            inputs:
              version: '18.19.0'
            displayName: 'Use Node.js 18.19.0'

          - script: |
              corepack enable
              corepack prepare yarn@stable --activate
            displayName: 'Install Yarn'

          - task: 'Cache@2'
            inputs:
              key: "$(Agent.JobName)|yarn.lock"
              path: 'node_modules'
            displayName: 'Cache for "node_modules"'
            continueOnError: true
          # TODO: duplicated code 3 times, 2 here and another at clone-and-move-opensearch-dashboards.yaml

          - task: 'Cache@2'
            inputs:
              key: "$(Agent.JobName)|sonar"
              path: "$(SONAR_USER_HOME)"
            displayName: 'Cache for SonarQube'
            continueOnError: true

          - task: 'DownloadPipelineArtifact@2'
            inputs:
              artifactName: 'coverage'
              targetPath: "$(Build.SourcesDirectory)/coverage"
            displayName: 'Download Coverage File'

          - script: |
              sed -i "s/\"extends\": \"\.\.\/\.\.\/tsconfig\.json\",/ /g" tsconfig.json
              yarn && yarn sonar

      - job: 'report_dependency_track'
        displayName: 'report:dependency-track'
        continueOnError: true
        # TODO: this is being repeated all over the place
        variables:
          PREFIX: ''
          REPORT_PATH: 'build/reports'
        steps:
          # TODO: duplicated code 3 times, 2 here and another at clone-and-move-opensearch-dashboards.yaml
          - task: 'UseNode@1'
            inputs:
              version: '18.19.0'
            displayName: 'Use Node.js 18.19.0'

          - script: |
              corepack enable
              corepack prepare yarn@stable --activate
            displayName: 'Install Yarn'

          - task: 'Cache@2'
            inputs:
              key: "$(Agent.JobName)|yarn.lock"
              path: 'node_modules'
            displayName: 'Cache for "node_modules"'
            continueOnError: true
          # TODO: duplicated code 3 times, 2 here and another at clone-and-move-opensearch-dashboards.yaml

          - script: |
              yarn && yarn sbom

          - template: '../../../global/abstracts/scripts-repo.yaml'
          - script: $(Scripts.Directory)/global/scripts/dependency-track/run.sh
