parameters:
  - name: 'RUN_BEFORE_MANAGEMENT'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_MANAGEMENT'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'management'
    displayName: 'management'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'report_sonarqube'
        displayName: 'report:sonarqube'
        variables:
          SONAR_USER_HOME: "$(Build.SourcesDirectory)/.sonar"
        steps:
          - template: 'steps/sonarqube.yaml'
            parameters:
              RUN_BEFORE_MANAGEMENT: ${{ parameters.RUN_BEFORE_MANAGEMENT }}
              RUN_AFTER_MANAGEMENT: ${{ parameters.RUN_AFTER_MANAGEMENT }}

      - job: 'report_dependency_track'
        displayName: 'report:dependency-track'
        variables:
          REPORT_PATH: 'build/reports'
        steps:
          - template: 'steps/dependency-track.yaml'
            parameters:
              RUN_BEFORE_MANAGEMENT: ${{ parameters.RUN_BEFORE_MANAGEMENT }}
              RUN_AFTER_MANAGEMENT: ${{ parameters.RUN_AFTER_MANAGEMENT }}
        continueOnError: true
