on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v6'

    - name: 'Setup Go 1.25'
      uses: 'actions/setup-go@v6'
      with:
        go-version: '1.25'
        cache-dependency-path: 'go.sum'

    - uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@main'

    - run: $SCRIPTS_DIR/global/scripts/golangci-lint/run.sh
      shell: 'bash'
