parameters:
  - name: 'RUN_BEFORE_CODE_CHECK'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_CODE_CHECK'
    type: 'string'
    default: 'echo "No after script"'
  - name: 'WORKING_DIRECTORY'
    type: 'string'
    default: ''

stages:
  - stage: 'code_check'
    displayName: 'code check (style/quality)'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'style_eslint'
        displayName: 'style:eslint'
        steps:
          - template: 'steps/eslint.yaml'
            parameters:
              WORKING_DIRECTORY: "${{ parameters.WORKING_DIRECTORY }}"
              RUN_BEFORE_CODE_CHECK: ${{ parameters.RUN_BEFORE_CODE_CHECK }}
              RUN_AFTER_CODE_CHECK: ${{ parameters.RUN_AFTER_CODE_CHECK }}
