parameters:
  - name: 'RUN_BEFORE_CODE_CHECK'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_CODE_CHECK'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'code_check'
    displayName: 'code check (style/quality)'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'style_eslint'
        displayName: 'style:eslint'
        steps:
          - script: |
              ${{ parameters.RUN_BEFORE_CODE_CHECK }}
            displayName: 'Run Before'

          - script: yarn lint

          - script: |
              ${{ parameters.RUN_AFTER_CODE_CHECK }}
            displayName: 'Run After'
