stages:
  - stage: 'code_check'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'code check (style/quality)'
    jobs:
      - job: 'style_eslint'
        displayName: 'style:eslint'
        steps:
          - template: '../../../global/abstracts/execute-command-opensearch-dashboards.yaml'
            parameters:
              TAG_NAME: '2.17.0'
              PLUGIN_NAME: 'app'
              COMMANDS: 'yarn && yarn lint'
