parameters:
  # optional parameter for heavy workloads within JS language
  - name: 'SELF_HOSTED_POOL'
    type: 'string'
    default: "$(SELF_HOSTED_POOL)"

stages:
  - stage: 'code_check'
    displayName: 'code check (style/quality)'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'style_eslint'
        displayName: 'style:eslint'
        ${{ if ne(parameters.SELF_HOSTED_POOL, '') }}:
          pool:
            name: "${{ parameters.SELF_HOSTED_POOL }}"
        steps:
          - template: '../../abstracts/execute-command-opensearch-dashboards.yaml'
            parameters:
              TAG_NAME: '2.18.0'
              PLUGIN_NAME: 'app'
              COMMANDS: 'yarn lint'
