parameters:
  - name: 'RUN_BEFORE_CODE_CHECK'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_CODE_CHECK'
    type: 'string'
    default: 'echo "No after script"'

  - name: 'RUN_BEFORE_TESTS'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_TESTS'
    type: 'string'
    default: 'echo "No after script"'

  - name: 'RUN_BEFORE_MANAGEMENT'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_MANAGEMENT'
    type: 'string'
    default: 'echo "No after script"'

  - name: 'RUN_BEFORE_DELIVERY'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DELIVERY'
    type: 'string'
    default: 'echo "No after script"'

  - name: 'RUN_BEFORE_DEPLOYMENT'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DEPLOYMENT'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - template: 'stages/10-code-check/yarn.yaml'
    parameters:
      RUN_BEFORE_CODE_CHECK: ${{ parameters.RUN_BEFORE_CODE_CHECK }}
      RUN_AFTER_CODE_CHECK: ${{ parameters.RUN_AFTER_CODE_CHECK }}
      WORKING_DIRECTORY: "$(System.DefaultWorkingDirectory)"

  - template: 'stages/20-security/yarn.yaml'

  - template: 'stages/30-tests/yarn.yaml'
    parameters:
      RUN_BEFORE_TESTS: ${{ parameters.RUN_BEFORE_TESTS }}
      RUN_AFTER_TESTS: ${{ parameters.RUN_AFTER_TESTS }}

  - template: 'stages/35-management/yarn.yaml'
    parameters:
      RUN_BEFORE_MANAGEMENT: ${{ parameters.RUN_BEFORE_MANAGEMENT }}
      RUN_AFTER_MANAGEMENT: ${{ parameters.RUN_AFTER_MANAGEMENT }}

  - template: 'stages/40-delivery/docker.yaml'
    parameters:
      RUN_BEFORE_DELIVERY: ${{ parameters.RUN_BEFORE_DELIVERY }}
      RUN_AFTER_DELIVERY: ${{ parameters.RUN_AFTER_DELIVERY }}

  - template: 'stages/50-deployment/k8s.yaml'
    parameters:
      RUN_BEFORE_DEPLOYMENT: ${{ parameters.RUN_BEFORE_DEPLOYMENT }}
      RUN_AFTER_DEPLOYMENT: ${{ parameters.RUN_AFTER_DEPLOYMENT }}
