include:
  - local: '/gitlab/java/abstracts/gradle-application.yaml'
  - local: '/gitlab/java/stages/30-tests/gradle.yaml'

variables:
  PREFIX: ''

.test:all:
  extends: '.gradle-application'

test:build:
  extends: '.test:all'
  stage: 'tests'
  script:
    - gradle build -x check -x test
  artifacts:
    paths:
      - '.gradle' # TODO: this should be removed, because the cache is going to handle this
      - 'build'
  rules: # TODO: this should be removed, because the pipeline should not depends of the cache
    - if: "$CI_MERGE_REQUEST_IID"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_TAG"
