stages:
    - stage: 'security_sca_sast'
      displayName: 'security (sca/sast)'
      condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
      jobs:
        - template: '../../../global/stages/20-security/docker.yaml'
          parameters:
            SEMGREP_LANGUAGE: 'java'

        - template: '../../../global/stages/20-security/codeql.yaml'
          parameters:
            CODEQL_LANGUAGE: 'java'

        - template: '../../../global/stages/20-security/hadolint.yaml'

        - template: '../../../global/stages/20-security/trivy.yaml'

        - template: '../../../global/stages/20-security/trivy-sca.yaml'

        - job: 'sca_dependency_check'
          displayName: 'sca:dependency-check'
          steps:
            - template: '../../abstracts/gradle.yaml'
            - script: echo "##vso[task.setvariable variable=WEEK_NUMBER]$(date +%Y-%W)"
              displayName: 'Get current week number'
            - task: 'Cache@2'
              inputs:
                key: "$(Agent.JobName)|owasp-nvd|$(WEEK_NUMBER)"
                restoreKeys: |
                  $(Agent.JobName)|owasp-nvd
                path: '.owasp'
              displayName: 'Cache NVD database'
              continueOnError: true
            - script: |
                mkdir -p '.owasp'
                export OWASP_PATH="$(pwd)/.owasp"
                ./gradlew dependencyCheckAnalyze
              displayName: 'Run OWASP Dependency-Check'
              env:
                NVD_API_KEY: $(NVD_API_KEY)
          continueOnError: true
