parameters:
  - name: 'DOCKER_BUILD_ARGS'
    type: 'string'
    default: ''
  - name: 'RUN_BEFORE_BUILD'
    type: 'string'
    default: ''

stages:
  - template: 'stages/10-code-check/go.yaml'
  - template: 'stages/20-security/go.yaml'
  - template: 'stages/30-tests/acr.yaml'
  - template: 'stages/35-management/go.yaml'
  - template: 'stages/40-delivery/docker.yaml'
  - template: 'stages/50-deployment/arm-container.yaml'
    parameters:
      DOCKER_BUILD_ARGS: '${{ parameters.DOCKER_BUILD_ARGS }}'
      RUN_BEFORE_BUILD: '${{ parameters.RUN_BEFORE_BUILD }}'
