parameters:
  # optional parameter for heavy workloads within JS language
  - name: 'SELF_HOSTED_POOL'
    type: 'string'
    default: "$(SELF_HOSTED_POOL)"

stages:
  - stage: 'tests'
    displayName: 'tests'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        steps:
          - template: '../../abstracts/execute-command-opensearch-dashboards.yaml'
            parameters:
              TAG_NAME: '3.2.0'
              PLUGIN_NAME: 'app'
              COMMANDS: 'yarn test:coverage'
              ARTIFACT_NAME: 'coverage'
              ARTIFACT_PATH: 'coverage'

          - task: 'PublishTestResults@2'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
            displayName: 'Publish Test Results'

          - task: 'PublishCodeCoverageResults@2'
            inputs:
              summaryFileLocation: 'cobertura.xml'
            displayName: 'Publish Code Coverage Results'

      - job: 'test_e2e'
        displayName: 'test:e2e'
        continueOnError: true
        ${{ if ne(parameters.SELF_HOSTED_POOL, '') }}:
          pool:
            name: "${{ parameters.SELF_HOSTED_POOL }}"
        steps:
          - template: '../../abstracts/run-test-e2e.yaml'
            parameters:
              TAG_NAME: '3.2.0'
              PLUGIN_NAME: 'app'
              # TODO: set the ports as an array of strings
              OS_PORT: '9200'
              OSD_PORT: '5603'

          - task: 'PublishTestResults@2'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
            displayName: 'Publish Test Results'

          - task: 'PublishCodeCoverageResults@2'
            inputs:
              summaryFileLocation: 'cobertura.xml'
            displayName: 'Publish Code Coverage Results'
