stages:
  - stage: 'tests'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'tests'
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        steps:
          - template: '../../../global/abstracts/execute-command-opensearch-dashboards.yaml'
            parameters:
              TAG_NAME: '2.17.0'
              PLUGIN_NAME: 'app'
              COMMANDS: 'yarn && yarn osd bootstrap && yarn test:coverage'
              ARTIFACT_NAME: 'coverage'
              ARTIFACT_PATH: 'coverage'

      - job: 'test_e2e'
        displayName: 'test:e2e'
        pool:
          name: $(E2E_POOL)
        steps:
          - template: '../../../global/abstracts/run-test-e2e.yaml'
            parameters:
              TAG_NAME: '2.17.0'
              PLUGIN_NAME: 'app'
              # TODO: set the ports as an array of strings
              OS_PORT: '9200'
              OSD_PORT: '5603'
