parameters:
  - name: 'SELF_HOSTED_POOL' # optional parameter for heavy workloads within JS language
    type: 'string'
    default: "$(SELF_HOSTED_POOL)"
  - name: 'WORKING_DIRECTORY'
    type: 'string'
    default: ''
  - name: 'RUN_BEFORE_TESTS'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_TESTS'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'tests'
    displayName: 'tests'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      jobs:
        - job: 'test_all'
          displayName: 'test:all'
          steps:
            - template: 'steps/test-all.yaml'
              parameters:
                WORKING_DIRECTORY: "${{ parameters.WORKING_DIRECTORY }}"
                RUN_BEFORE_TESTS: ${{ parameters.RUN_BEFORE_TESTS }}
                RUN_AFTER_TESTS: ${{ parameters.RUN_AFTER_TESTS }}

        - job: 'test_e2e'
          displayName: 'test:e2e'
          continueOnError: true
          ${{ if ne(parameters.SELF_HOSTED_POOL, '') }}:
            pool:
              name: "${{ parameters.SELF_HOSTED_POOL }}"
          steps:
            - template: 'jobs/test-e2e.yaml'
              parameters:
                WORKING_DIRECTORY: "${{ parameters.WORKING_DIRECTORY }}"
                RUN_BEFORE_TESTS: ${{ parameters.RUN_BEFORE_TESTS }}
                RUN_AFTER_TESTS: ${{ parameters.RUN_AFTER_TESTS }}
