jobs:
  - job: 'report_sonarqube'
    displayName: 'report:sonarqube'
    container:
      image: 'sonarsource/sonar-scanner-cli:latest'
      options: '--user root' # TODO: workaround for Azure DevOps error
    variables:
      GIT_DEPTH: '0'
      SONAR_USER_HOME: "$(Build.SourcesDirectory)/.sonar"
    steps:
      - checkout: 'self'
        fetchDepth: 0
        fetchTags: true

      - task: 'DownloadPipelineArtifact@2'
        inputs:
          artifactName: 'coverage'
          targetPath: '$(Build.SourcesDirectory)'
        displayName: 'Download Coverage File'
        continueOnError: true

      - task: 'Cache@2'
        inputs:
          key: "$(Agent.JobName)|sonar"
          path: "$(SONAR_USER_HOME)"
        displayName: 'Cache for SonarQube'
        continueOnError: true

      - template: '../../abstracts/scripts-repo.yaml'
      - script: $(Scripts.Directory)/global/scripts/sonarqube/run.sh
