include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/terraform/terra.yaml'

# Optional: Override variables
# variables:
#   SONAR_HOST_URL: 'https://sonar.example.com'
