parameters:
  - name: 'WORKING_DIRECTORY'
    type: 'string'
    default: ''
  - name: 'RUN_BEFORE_DELIVERY'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DELIVERY'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'delivery'
    displayName: 'delivery'
    condition: and(not(failed()), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        variables:
          DOCKER_CACHE_DIR: '$(Agent.TempDirectory)/docker-cache'
          BUILD_ARTIFACT_NAME: 'build'
          BUILD_ARTIFACT_PATH: 'build'
        steps:
          - template: 'steps/delivery.yaml'
            parameters:
              WORKING_DIRECTORY: "${{ parameters.WORKING_DIRECTORY }}"
              RUN_BEFORE_DELIVERY: ${{ parameters.RUN_BEFORE_DELIVERY }}
              RUN_AFTER_DELIVERY: ${{ parameters.RUN_AFTER_DELIVERY }}
        continueOnError: false

      - template: '../../../global/stages/40-delivery/release.yaml'
