parameters:
  - name: 'RUN_BEFORE_DELIVERY'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DELIVERY'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'delivery'
    displayName: 'delivery'
    condition: and(not(failed()), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        variables:
          DOCKER_CACHE_DIR: '$(Agent.TempDirectory)/docker-cache'
          BUILD_ARTIFACT_NAME: 'build'
          BUILD_ARTIFACT_PATH: 'build'
        steps:
          - script: |
              ${{ parameters.RUN_BEFORE_DELIVERY }}
            displayName: 'Run Before'

          - script: yarn build

          - script: |
              ${{ parameters.RUN_AFTER_DELIVERY }}
            displayName: 'Run After'

          - task: 'DownloadPipelineArtifact@2'
            inputs:
              artifactName: "$(BUILD_ARTIFACT_NAME)"
              targetPath: 'build'
            displayName: 'Download Build Artifact'

          - template: '../../../global/stages/40-delivery/docker.yaml'
            parameters:
              DOCKER_FILE: '.ci/40-delivery/app.Dockerfile'
              DOCKER_CACHE_DIR: '$(DOCKER_CACHE_DIR)'
              CONTAINER_REGISTRY_SERVER: '$(CONTAINER_REGISTRY_SERVER)'
              CONTAINER_REGISTRY_SERVICE_CONNECTION: '$(CONTAINER_REGISTRY_SERVICE_CONNECTION)'

        continueOnError: false
      - template: '../../../global/stages/40-delivery/release.yaml'
