parameters:
  - name: 'WORKING_DIRECTORY'
    type: 'string'
    default: ''
  - name: 'RUN_BEFORE_DELIVERY'
    type: 'string'
    default: 'echo "No before script"'
  - name: 'RUN_AFTER_DELIVERY'
    type: 'string'
    default: 'echo "No after script"'

stages:
  - stage: 'delivery'
    displayName: 'delivery'
    condition: and(not(failed()), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'delivery_build'
        displayName: 'delivery > build'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        variables:
          DOCKER_CACHE_DIR: "$(Agent.TempDirectory)/docker-cache"
          BUILD_ARTIFACT_NAME: 'build'
          BUILD_ARTIFACT_PATH: 'build'
        steps:
          - template: 'steps/delivery.yaml'
            parameters:
              WORKING_DIRECTORY: "${{ parameters.WORKING_DIRECTORY }}"
              RUN_BEFORE_DELIVERY: ${{ parameters.RUN_BEFORE_DELIVERY }}
              RUN_AFTER_DELIVERY: ${{ parameters.RUN_AFTER_DELIVERY }}
        continueOnError: false

      - job: 'delivery_retag'
        displayName: 'delivery > retag'
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        steps:
          - template: '../../../global/stages/40-delivery/docker-retag.yaml'
            parameters:
              CONTAINER_REGISTRY_SERVER: "$(CONTAINER_REGISTRY_SERVER)"
              CONTAINER_REGISTRY_SERVICE_CONNECTION: "$(CONTAINER_REGISTRY_SERVICE_CONNECTION)"
              SOURCE_TAG: 'latest'
              TARGET_TAG: '$(Build.SourceBranchName)'

      - template: '../../../global/stages/40-delivery/release.yaml'
