stages:
  - stage: 'delivery'
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'delivery'
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        steps:
          - template: '../../../global/abstracts/clone-and-move-plugin-steps.yml'
            parameters:
              TAG_NAME: '2.13.0'
              PLUGIN_NAME: 'app'
              COMMANDS: 'yarn osd bootstrap && yarn build'
              ARTIFACT_NAME: 'build'
              ARTIFACT_PATH: 'build'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'build'
              downloadPath: '.'
          - task: Docker@2
            displayName: 'Docker Login'
            inputs:
              command: 'login'
              containerRegistry: '$(DOCKER_REGISTRY_ENDPOINT)'
          - script: |
              docker buildx create --use

              TAGS="$(DOCKER_CONTAINER_IMAGE):latest"
              if [[ "$(Build.SourceBranch)" == refs/tags/* ]]; then
                TAGS="$TAGS -t $(DOCKER_CONTAINER_IMAGE):$(Build.SourceBranchName)"
                echo "##vso[task.setvariable variable=DOCKER_CONTAINER_TAG;isOutput=true]$(Build.SourceBranchName)"
              else
                echo "##vso[task.setvariable variable=DOCKER_CONTAINER_TAG;isOutput=true]latest"
              fi

              docker buildx build --platform linux/amd64,linux/arm64 -t $TAGS --push .
            name: 'build'
        continueOnError: false
      - template: '../../../global/stages/40-delivery/release.yaml'
