stages:
  - stage: 'delivery'
    displayName: 'delivery'
    # condition: and(not(failed()), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        variables:
          DOCKER_CACHE_DIR: '$(Agent.TempDirectory)/docker-cache'
          BUILD_ARTIFACT_NAME: 'build'
          BUILD_ARTIFACT_PATH: 'build'
        steps:
          - template: '../../abstracts/execute-command-opensearch-dashboards.yaml'
            parameters:
              TAG_NAME: '2.19.1'
              THEME_TAG_NAME: '1.19.0'
              PLUGIN_NAME: 'app'
              COMMANDS: 'yarn build'
              ARTIFACT_NAME: "$(BUILD_ARTIFACT_NAME)"
              ARTIFACT_PATH: "$(BUILD_ARTIFACT_PATH)"

          - task: 'DownloadPipelineArtifact@2'
            inputs:
              artifactName: "$(BUILD_ARTIFACT_NAME)"
              targetPath: 'build'
            displayName: 'Download Build Artifact'

          - template: '../../../global/stages/40-delivery/docker.yaml'
            parameters:
              DOCKER_FILE: '.ci/40-delivery/app.Dockerfile'
              DOCKER_CACHE_DIR: '$(DOCKER_CACHE_DIR)'
              CONTAINER_REGISTRY_SERVER: '$(CONTAINER_REGISTRY_SERVER)'
              CONTAINER_REGISTRY_SERVICE_CONNECTION: '$(CONTAINER_REGISTRY_SERVICE_CONNECTION)'

        continueOnError: false
      - template: '../../../global/stages/40-delivery/release.yaml'
