on:
  workflow_call:

inputs:
  semgrep_lang:
    description: 'Sempgrep language to be used as default source'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v6'

    - name: 'Get Scripts'
      uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@main'

    - name: 'Execute'
      shell: 'bash'
      run: $SCRIPTS_DIR/global/scripts/semgrep/run.sh "${{ inputs.semgrep_lang }}"

    - name: 'Upload Report'
      uses: 'actions/upload-artifact@v6'
      with:
        name: 'semgrep'
        path: 'build/reports/semgrep.json'
        if-no-files-found: 'error'
        overwrite: 'true'
        retention-days: 10
      if: always()
