include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/fix/test/gitlab/dotnet/stages/30-tests/msbuild.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/fix/test/gitlab/global/stages/40-delivery/release.yaml'

stages:
  - 'code check (style/quality)'
  - 'security (sca/sast)'
  - 'tests'
  - 'management'
  - 'delivery'
