#!/usr/bin/env sh
# Writes the shared ignore rules into a consumer's `.gitignore`, inside a delimited
# block, and verifies that block is current.
#
# Why this is generated rather than referenced: git has no `include` directive for
# ignore files, and it refuses to follow a symlinked `.gitignore` outright. The two
# mechanisms that DO take an external file -- `core.excludesFile` and
# `$GIT_DIR/info/exclude` -- are local to a clone, so they are invisible to CI, to a
# fresh checkout, and to every bot that clones and runs `git add -A`. That is exactly
# the population that commits a stray report file, so the rules have to be committed.
#
# Generating them keeps the single definition; `--check` restores the enforcement an
# `include` would have given for free.
#
# Usage:
#   run.sh [--check] [project_dir]
#
#   --check   report drift and exit 1 instead of writing (for CI)

set -eu

if [ -z "${SCRIPTS_DIR:-}" ]; then
  SCRIPTS_DIR="$(echo "$(dirname "$(realpath "$0")")" | sed 's|\(.*pipelines\).*|\1|')"
  export SCRIPTS_DIR
fi

BEGIN_MARK='# >>> pipelines:begin'
END_MARK='# <<< pipelines:end'

CHECK=0
PROJECT_DIR='.'
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    -*) echo "unknown option: $arg" >&2; exit 2 ;;
    *) PROJECT_DIR="$arg" ;;
  esac
done

cd "$PROJECT_DIR" || { echo "no such directory: $PROJECT_DIR" >&2; exit 2; }

FRAGMENT_DIR="$SCRIPTS_DIR/global/gitignore"
[ -d "$FRAGMENT_DIR" ] || { echo "missing fragment directory: $FRAGMENT_DIR" >&2; exit 2; }

# Which language fragments apply is not new configuration to keep in step: the
# project's Makefile already declares the pipeline it consumes, so the `.mk` files it
# includes are the answer. A language with no fragment of its own writes only under
# REPORT_PATH, which `common` already covers, so a miss here is not a gap.
fragments='common'
if [ -f Makefile ]; then
  # Word-splitting is deliberate and safe: the pattern captures [a-z0-9-] only, so no
  # name can carry a space or a glob. Piping into `while read` instead would put the
  # loop in a subshell, and the `fragments` accumulation below would be discarded.
  # shellcheck disable=SC2013
  for name in $(sed -n 's|.*makefiles/\([a-z0-9-]*\)\.mk.*|\1|p' Makefile | sort -u); do
    [ "$name" = 'common' ] && continue
    [ -f "$FRAGMENT_DIR/$name" ] || continue
    fragments="$fragments $name"
  done
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
desired="$work/desired"
block="$work/block"

{
  echo "$BEGIN_MARK"
  echo '# Generated by `make gitignore` from rios0rios0/pipelines. Do not edit inside'
  echo '# this block: it is rewritten in place, and CI fails when it is out of date.'
  echo '#'
  echo '# These are the files the pipeline itself writes into this working tree. The'
  echo '# block sits first on purpose -- gitignore resolves last-match-wins, so any'
  echo '# entry BELOW it, including a `!` negation, overrides what it says here.'
  for name in $fragments; do
    echo ''
    sed 's/[[:space:]]*$//' "$FRAGMENT_DIR/$name"
  done
  echo "$END_MARK"
} > "$block"

# Refuse to touch a file whose markers are not a single well-formed pair.
#
# The removal below drops every line between the markers, so a file carrying a begin marker
# with no end -- a truncated write, a merge conflict resolved badly, a hand edit that deleted
# one line -- would have the rest of the file read as block content and thrown away. That is
# silent data loss in the one place this script promises never to touch: the project's own
# entries. Refusing costs a human one look at the file; rewriting costs them entries they may
# not notice are gone until something they meant to ignore is committed.
#
# Duplicated or out-of-order markers are refused for the same reason. They are recoverable in
# principle, but only by guessing which block the project meant to keep, and a wrong guess is
# indistinguishable from the malformed state that caused it.
if [ -f .gitignore ]; then
  begins="$(grep -cxF "$BEGIN_MARK" .gitignore || true)"
  ends="$(grep -cxF "$END_MARK" .gitignore || true)"
  begin_line="$(grep -nxF "$BEGIN_MARK" .gitignore | head -1 | cut -d: -f1)"
  end_line="$(grep -nxF "$END_MARK" .gitignore | head -1 | cut -d: -f1)"

  malformed=''
  if [ "$begins" -gt 1 ] || [ "$ends" -gt 1 ]; then
    malformed="found $begins begin and $ends end markers; expected at most one of each"
  elif [ "$begins" -ne "$ends" ]; then
    malformed="found $begins begin and $ends end markers; they must come as a pair"
  elif [ "$begins" -eq 1 ] && [ "$begin_line" -gt "$end_line" ]; then
    malformed="the end marker (line $end_line) comes before the begin marker (line $begin_line)"
  fi

  if [ -n "$malformed" ]; then
    echo "ERROR: .gitignore has a malformed pipelines block: $malformed." >&2
    echo "" >&2
    echo "  Refusing to rewrite it, because the entries outside the block cannot be told" >&2
    echo "  apart from its contents -- continuing would risk deleting your own entries." >&2
    echo "" >&2
    echo "  Fix the markers by hand, or delete the block entirely, then run this again:" >&2
    echo "    $BEGIN_MARK" >&2
    echo "    $END_MARK" >&2
    exit 2
  fi
fi

# Everything outside the markers is the project's own and is copied through
# untouched. A file with no block yet keeps all of its content, below the new one.
rest="$work/rest"
if [ -f .gitignore ]; then
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip   { print }
  ' .gitignore > "$rest"
else
  : > "$rest"
fi

# Collapse leading blank lines left behind by removing the old block, so repeated
# runs converge instead of growing a gap.
sed '/./,$!d' "$rest" > "$rest.trimmed"
mv "$rest.trimmed" "$rest"

cat "$block" > "$desired"
if [ -s "$rest" ]; then
  echo '' >> "$desired"
  cat "$rest" >> "$desired"
fi

if [ "$CHECK" -eq 1 ]; then
  if [ -f .gitignore ] && cmp -s "$desired" .gitignore; then
    echo "OK: .gitignore is in step with the shared ignore rules."
    exit 0
  fi
  echo "ERROR: .gitignore does not match the shared ignore rules." >&2
  echo "" >&2
  if [ -f .gitignore ]; then
    diff -u .gitignore "$desired" 2>/dev/null | sed 's|'"$desired"'|.gitignore (expected)|' >&2 || true
  else
    echo "  the file does not exist yet" >&2
  fi
  echo "" >&2
  echo "Run 'make gitignore' and commit the result." >&2
  exit 1
fi

if [ -f .gitignore ] && cmp -s "$desired" .gitignore; then
  echo "Already up to date: .gitignore ($(echo "$fragments" | tr ' ' ',' ))"
  exit 0
fi

cp "$desired" .gitignore
echo "Updated .gitignore from fragments: $(echo "$fragments" | tr ' ' ',' )"
