#!/usr/bin/env python3
"""Generate the shared `variable` declarations each stack needs.

A Terragrunt repo is a set of root modules, so an input every stack receives has
to be DECLARED in every stack. That is inherent to the layout, but the
declarations are not: measured across one four-repo fabric, `environment` was
declared 47 times, `cloudflare_api_token` 27, `cluster_uuid` 17. The bodies had
drifted into near-copies of each other, which is worse than either one shared
body or 47 deliberate ones -- nobody can tell which differences are meaningful.

This tool keeps ONE canonical body per name in a per-repo catalog and writes the
subset each stack actually uses into `stacks/<stack>/variables-shared.tf`.

WHY GENERATE-AND-COMMIT RATHER THAN A TERRAGRUNT `generate` BLOCK

A `generate` block would emit into `.terragrunt-cache` at plan time, where three
CI gates cannot see it: the order-check's dead-input detection reads
`stacks/*.tf` from the source tree, the opt-in `terraform validate` tier runs
against `stacks/` without going through Terragrunt, and AST-based tests parse
`variables.tf` directly. Committed output keeps all three working, and matches
the house precedent set by the sibling `tftest-gen`.

WHY A SEPARATE FILE RATHER THAN APPENDING TO `variables.tf`

The order-check applies its `// SET ON .HCL` / `// SET ON .ENV` marker rule to
`stacks/*/variables.tf` only, while its dead-input scan globs `*.tf`. Writing to
a sibling file therefore keeps generated content exempt from an ordering rule a
generator cannot satisfy, while remaining visible to the gate that matters.

WHAT IT WILL NOT DO

It never rewrites a hand-written declaration. If a stack declares a catalogued
name in its own `variables.tf`, that stack is REPORTED and skipped -- the local
body may say something the canonical one does not, and a generator that
overwrites prose destroys information rather than duplication. (The sibling
generator learned this the expensive way: an unchecked marker once let a rerun
destroy every hand-written smoke test.)

Usage:
    gen_shared_variables.py --repo-dir /path [--check] [--report]

    --check   exit non-zero if the committed output differs from what would be
              generated; writes nothing. This is the CI gate.
    --report  print what would change and exit 0; writes nothing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

MARKER = (
    "# AUTOGENERATED by var-catalog from .terraform-var-catalog.hcl -- do not edit.\n"
    "# Regenerate with the var-catalog runner (a consumer may wrap it in a make target)."
)
OUTPUT_NAME = "variables-shared.tf"
CATALOG_NAME = ".terraform-var-catalog.hcl"

# `variable "name" {` at column 0 -- the declaration form, not a `var.` use.
DECL_RE = re.compile(r'^variable\s+"([A-Za-z0-9_-]+)"\s*\{', re.M)
# `var.<name>`, stopping at the first non-identifier so `var.placement.cloud`
# yields `placement`.
USE_RE = re.compile(r"\bvar\.([A-Za-z_][A-Za-z0-9_]*)")
# One `name = <<-EOT ... EOT` entry per catalogued variable.
ENTRY_RE = re.compile(
    r'^\s*([A-Za-z0-9_-]+)\s*=\s*<<-?([A-Za-z0-9_]+)\s*\n(.*?)^\s*\2\s*$',
    re.M | re.S,
)


def strip_comments(text: str) -> str:
    """Remove `#`, `//` and `/* */` comments, respecting string literals.

    Load-bearing, not tidiness: these files are comment-dense, and a comment
    that merely MENTIONS `var.tags` would otherwise resurrect a declaration the
    stack no longer uses -- reintroducing the dead code this tool removes.

    String awareness is equally load-bearing, and was learned the hard way: a
    naive scan treats the `//` in `"https://api.example/..."` as a comment start,
    truncates the line, and loses the `${var.environment}` interpolation after
    it. The stack then gets no declaration for a variable it genuinely uses.
    That failure is at least loud -- `terraform validate` reports an undeclared
    input variable -- but it should not happen at all.
    """
    out = []
    in_block = False
    for line in text.split("\n"):
        in_string = False
        i = 0
        kept = []
        while i < len(line):
            ch = line[i]
            if in_block:
                # A block comment ends only outside a string; a `*/` inside one
                # cannot close it, because it was never opened there.
                if line.startswith("*/", i):
                    in_block = False
                    i += 2
                    continue
                i += 1
                continue
            if ch == "\\" and in_string:
                kept.append(line[i:i + 2])
                i += 2
                continue
            if ch == '"':
                in_string = not in_string
            elif not in_string:
                # Block comments are handled HERE, in the same string-aware pass
                # as `#` and `//`, not by a regex beforehand. A pre-pass would
                # delete a `/* */` sequence sitting inside a quoted string and
                # take any `var.<name>` after it on the line with it.
                if line.startswith("/*", i):
                    in_block = True
                    i += 2
                    continue
                if ch == "#" or line.startswith("//", i):
                    break
            kept.append(ch)
            i += 1
        out.append("".join(kept))
    return "\n".join(out)


def dedent(block: str) -> str:
    """Strip the common leading indentation, the way HCL's `<<-` heredoc does.

    Load-bearing rather than cosmetic. A `variable` block emitted with leading
    whitespace is still valid Terraform, but it is no longer a TOP-LEVEL block
    to a scanner that anchors on column 0 -- which is exactly how the sibling
    order-check collects declared variable names. Indented output therefore
    parses fine and then gets reported as a dead input for every stack, a
    failure whose message points nowhere near its cause.
    """
    lines = block.split("\n")
    widths = [len(l) - len(l.lstrip()) for l in lines if l.strip()]
    pad = min(widths) if widths else 0
    return "\n".join(l[pad:] if l.strip() else "" for l in lines)


def load_catalog(repo: Path) -> dict[str, str]:
    path = repo / CATALOG_NAME
    if not path.is_file():
        return {}
    body = path.read_text()
    catalog: dict[str, str] = {}
    for name, _tag, decl in ENTRY_RE.findall(body):
        catalog[name] = dedent(decl.rstrip("\n"))
    return catalog


def stack_dirs(repo: Path) -> list[Path]:
    """Every directory under `stacks/` holding at least one `.tf` file.

    Deliberately the SAME rule the sibling validate tier uses, rather than
    "contains a main.tf": a root module is a directory Terraform can be pointed
    at, and nothing requires its entry file to be called `main.tf`. Keying off
    that name would silently skip a stack whose entry point is spelled
    differently -- no declarations generated, no `--check` coverage, and a
    success report.

    `.terraform` is excluded because `terraform init` vendors module sources
    there; those are other repos' files.
    """
    stacks = repo / "stacks"
    if not stacks.is_dir():
        return []
    return sorted({
        tf.parent for tf in stacks.rglob("*.tf")
        if ".terraform" not in tf.parts
    })


def analyse(stack: Path, catalog: dict[str, str]) -> tuple[list[str], list[str]]:
    """Return (names to generate, names skipped because hand-written)."""
    used: set[str] = set()
    declared_locally: set[str] = set()
    for tf in sorted(stack.glob("*.tf")):
        if tf.name == OUTPUT_NAME:
            continue
        raw = tf.read_text()
        used |= set(USE_RE.findall(strip_comments(raw)))
        declared_locally |= set(DECL_RE.findall(raw))
    wanted = sorted(n for n in catalog if n in used)
    generate = [n for n in wanted if n not in declared_locally]
    skipped = [n for n in wanted if n in declared_locally]
    return generate, skipped


def render(names: list[str], catalog: dict[str, str]) -> str:
    blocks = "\n\n".join(catalog[n] for n in names)
    return f"{MARKER}\n\n{blocks}\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-dir", default=".")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    repo = Path(args.repo_dir).resolve()
    catalog = load_catalog(repo)
    if not catalog:
        print(f"var-catalog: no {CATALOG_NAME} in {repo}; nothing to do")
        return 0

    drift: list[str] = []
    preserved: list[str] = []
    written = 0

    for stack in stack_dirs(repo):
        rel = stack.relative_to(repo)
        generate, skipped = analyse(stack, catalog)
        preserved += [f"{rel}: {n}" for n in skipped]
        target = stack / OUTPUT_NAME
        want = render(generate, catalog) if generate else ""
        have = target.read_text() if target.is_file() else ""

        if want == have:
            continue
        drift.append(str(rel / OUTPUT_NAME))
        if args.check or args.report:
            continue
        if want:
            target.write_text(want)
        elif target.is_file():
            target.unlink()
        written += 1

    # Not in `--check`: that mode's output is quoted verbatim into a CI failure
    # message, and burying the one actionable line under a dozen informational
    # ones is how a good message stops being read.
    if not args.check:
        for entry in preserved:
            print(f"var-catalog: PRESERVED hand-written declaration -- {entry}")

    if args.check and drift:
        print("var-catalog: generated files are out of date:", file=sys.stderr)
        for d in drift:
            print(f"  {d}", file=sys.stderr)
        print("re-run the var-catalog runner and commit the result", file=sys.stderr)
        return 1
    if args.report:
        print(f"var-catalog: {len(drift)} file(s) would change")
        for d in drift:
            print(f"  {d}")
        return 0
    if args.check:
        print("var-catalog: generated files are up to date")
        return 0

    print(f"var-catalog: wrote {written} file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
