stages:
  - stage: 'deployment'
    displayName: 'deployment'
    condition: and(not(failed()), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    jobs:
      - job: 'deployment'
        displayName: 'deployment'
        steps:
          - script: |
              resourceGroupName="$(ENVIRONMENT)-rg-$(RESOURCE_GROUP_NAME)-$(AZM_LOCATION)"
              echo "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"

              imageName=$(REGISTRY_SERVER)/$(Build.Repository.Name)

              TAG="latest"
              if [[ "$(Build.SourceBranch)" == refs/tags/* ]]; then
                TAG="$(Build.SourceBranchName)"
              fi

              echo "##vso[task.setvariable variable=DOCKER_CONTAINER_TAG;isOutput=true]$TAG"
              IMAGE_NAME="$imageName:$TAG"

              echo "##vso[task.setvariable variable=CONTAINER_IMAGE]$IMAGE_NAME"

              resourceGroupExists=$(az group exists --name $resourceGroupName)
              echo "##vso[task.setvariable variable=resourceGroupExists]$resourceGroupExists"
            displayName: 'Set Resource Group Name'
          - template: '../../../global/stages/50-deployment/arm-parameters.yaml'
            parameters:
              armTemplateFile: 'azuredeploy.json'
          - task: 'AzureResourceGroupDeployment@2'
            inputs:
              location: "$(AZM_LOCATION)"
              action: 'Create Or Update Resource Group'
              azureSubscription: "$(AZM_SERVICE_CONNECTION)"
              resourceGroupName: "$(resourceGroupName)"
              deploymentMode: 'Incremental'
              deploymentOutputs: 'AZURE_DEPLOY_OUTPUTS'
              csmFile: '$(Build.SourcesDirectory)/azuredeploy.json'
              csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'  
            displayName: 'Deploy Container to Azure'
