stages:
  - stage: 'deployment'
    displayName: 'deployment'
    condition: and(not(failed()), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    jobs:
      - job: 'deployment'
        displayName: 'deployment'
        variables:
          MIGRATIONS_CACHE: "$(Build.SourcesDirectory)/.migration"
          GOPATH: "$(Pipeline.Workspace)/.go"
          SEEDERS_CACHE: "$(Build.SourcesDirectory)/.seeder"
          AZURE_DEPLOY_CACHE: "$(Build.SourcesDirectory)/.azuredeploy"
          PIPELINE_FIREWALL_NAME: 'PipelineFirewall_$(date +"%Y%m%d%H%M%S")'
        steps:
          - template: '../../../global/stages/50-deployment/fixed.yaml'
            parameters:
              PIPELINE_FIREWALL_NAME: '$(PIPELINE_FIREWALL_NAME)'
              AZM_FUNCTION_NAME: '$(AZM_FUNCTION_NAME)'
              AZM_LOCATION: '$(AZM_LOCATION)'
              AZM_SERVICE_CONNECTION: '$(AZM_SERVICE_CONNECTION)'
              ENVIRONMENT: '$(ENVIRONMENT)'
              INBOUND_ALLOWED_IPS: '$(INBOUND_ALLOWED_IPS)'
