parameters:
  - name: 'LAMBDA_FUNCTION_NAME'
    type: 'string'
  - name: 'AWS_REGION'
    type: 'string'
    default: 'us-east-1'
  - name: 'DEPLOY_STRATEGY'
    type: 'string'
    default: 'zip'
  - name: 'AWS_SERVICE_CONNECTION'
    type: 'string'
    default: ''
  - name: 'LAMBDA_RUNTIME'
    type: 'string'
    default: 'provided.al2023'
  - name: 'LAMBDA_HANDLER'
    type: 'string'
    default: 'bootstrap'
  - name: 'LAMBDA_TIMEOUT'
    type: 'string'
    default: '30'
  - name: 'LAMBDA_MEMORY_SIZE'
    type: 'string'
    default: '128'
  - name: 'LAMBDA_ENV_VARS'
    type: 'string'
    default: ''
  - name: 'CREATE_IF_MISSING'
    type: 'boolean'
    default: false
  - name: 'SAM_CONFIG_ENV'
    type: 'string'
    default: 'default'

stages:
  - stage: 'deployment'
    displayName: 'deployment'
    condition: and(not(failed()), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    jobs:
      - job: 'deployment'
        displayName: 'deployment'
        container: 'ghcr.io/rios0rios0/pipelines/awscli:latest'
        steps:
          - ${{ if eq(parameters.DEPLOY_STRATEGY, 'zip') }}:
            - task: 'DownloadPipelineArtifact@2'
              inputs:
                artifact: 'lambda-function-zip'
                path: '$(Build.SourcesDirectory)'
              displayName: 'Download Lambda ZIP Artifact'

          - ${{ if eq(parameters.DEPLOY_STRATEGY, 'sam') }}:
            - task: 'DownloadPipelineArtifact@2'
              inputs:
                artifact: 'lambda-sam-template'
                path: '$(Build.SourcesDirectory)'
              displayName: 'Download SAM Template Artifact'

          - ${{ if ne(parameters.AWS_SERVICE_CONNECTION, '') }}:
            - task: 'AWSShellScript@1'
              displayName: 'Deploy Lambda Function (AWS Service Connection)'
              inputs:
                awsCredentials: '${{ parameters.AWS_SERVICE_CONNECTION }}'
                regionName: '${{ parameters.AWS_REGION }}'
                scriptType: 'inline'
                inlineScript: |
                  set -e
                  
                  ${{ if eq(parameters.DEPLOY_STRATEGY, 'zip') }}:
                  echo "Deploying Lambda function via AWS CLI..."
                  
                  # Check if function exists
                  if aws lambda get-function --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} --region ${{ parameters.AWS_REGION }} 2>/dev/null; then
                    echo "Updating existing Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"
                    aws lambda update-function-code \
                      --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                      --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                      --region ${{ parameters.AWS_REGION }}
                    
                    # Update configuration if parameters are provided
                    ${{ if ne(parameters.LAMBDA_ENV_VARS, '') }}:
                    aws lambda update-function-configuration \
                      --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                      --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                      --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                      --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                      --region ${{ parameters.AWS_REGION }}
                    ${{ else }}:
                    aws lambda update-function-configuration \
                      --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                      --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                      --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                      --region ${{ parameters.AWS_REGION }}
                  ${{ if eq(parameters.CREATE_IF_MISSING, true) }}:
                  elif [ "${{ parameters.CREATE_IF_MISSING }}" = "true" ]; then
                    echo "Creating new Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"
                    
                    # Note: Creating a Lambda function requires IAM role ARN
                    # This should be provided via environment variables or parameters
                    if [ -z "$LAMBDA_ROLE_ARN" ]; then
                      echo "ERROR: LAMBDA_ROLE_ARN environment variable is required to create a new Lambda function"
                      exit 1
                    fi
                    
                    aws lambda create-function \
                      --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                      --runtime ${{ parameters.LAMBDA_RUNTIME }} \
                      --handler ${{ parameters.LAMBDA_HANDLER }} \
                      --role "$LAMBDA_ROLE_ARN" \
                      --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                      --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                      --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                      ${{ if ne(parameters.LAMBDA_ENV_VARS, '') }} \
                      --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                      --region ${{ parameters.AWS_REGION }}
                  else
                    echo "ERROR: Lambda function ${{ parameters.LAMBDA_FUNCTION_NAME }} does not exist and CREATE_IF_MISSING is false"
                    exit 1
                  fi
                  
                  echo "Lambda function deployed successfully"
                  ${{ if eq(parameters.DEPLOY_STRATEGY, 'sam') }}:
                  echo "Deploying Lambda function via AWS SAM..."
                  sam deploy \
                    --template-file $(Build.SourcesDirectory)/packaged.yaml \
                    --config-env ${{ parameters.SAM_CONFIG_ENV }} \
                    --no-confirm-changeset \
                    --region ${{ parameters.AWS_REGION }}

          - ${{ if eq(parameters.AWS_SERVICE_CONNECTION, '') }}:
            - script: |
                set -e
                
                # Validate AWS credentials are set via environment variables
                if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
                  echo "ERROR: AWS credentials not found. Please configure AWS_SERVICE_CONNECTION or set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
                  exit 1
                fi
                
                ${{ if eq(parameters.DEPLOY_STRATEGY, 'zip') }}:
                echo "Deploying Lambda function via AWS CLI..."
                
                # Check if function exists
                if aws lambda get-function --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} --region ${{ parameters.AWS_REGION }} 2>/dev/null; then
                  echo "Updating existing Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"
                  aws lambda update-function-code \
                    --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                    --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                    --region ${{ parameters.AWS_REGION }}
                  
                  # Update configuration if parameters are provided
                  ${{ if ne(parameters.LAMBDA_ENV_VARS, '') }}:
                  aws lambda update-function-configuration \
                    --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                    --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                    --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                    --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                    --region ${{ parameters.AWS_REGION }}
                  ${{ else }}:
                  aws lambda update-function-configuration \
                    --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                    --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                    --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                    --region ${{ parameters.AWS_REGION }}
                ${{ if eq(parameters.CREATE_IF_MISSING, true) }}:
                elif [ "${{ parameters.CREATE_IF_MISSING }}" = "true" ]; then
                  echo "Creating new Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"
                  
                  # Note: Creating a Lambda function requires IAM role ARN
                  # This should be provided via environment variables or parameters
                  if [ -z "$LAMBDA_ROLE_ARN" ]; then
                    echo "ERROR: LAMBDA_ROLE_ARN environment variable is required to create a new Lambda function"
                    exit 1
                  fi
                  
                  aws lambda create-function \
                    --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                    --runtime ${{ parameters.LAMBDA_RUNTIME }} \
                    --handler ${{ parameters.LAMBDA_HANDLER }} \
                    --role "$LAMBDA_ROLE_ARN" \
                    --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                    --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                    --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                    ${{ if ne(parameters.LAMBDA_ENV_VARS, '') }} \
                    --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                    --region ${{ parameters.AWS_REGION }}
                else
                  echo "ERROR: Lambda function ${{ parameters.LAMBDA_FUNCTION_NAME }} does not exist and CREATE_IF_MISSING is false"
                  exit 1
                fi
                
                echo "Lambda function deployed successfully"
                ${{ if eq(parameters.DEPLOY_STRATEGY, 'sam') }}:
                echo "Deploying Lambda function via AWS SAM..."
                sam deploy \
                  --template-file $(Build.SourcesDirectory)/packaged.yaml \
                  --config-env ${{ parameters.SAM_CONFIG_ENV }} \
                  --no-confirm-changeset \
                  --region ${{ parameters.AWS_REGION }}
              displayName: 'Deploy Lambda Function (Environment Variables)'
