parameters:
  - name: 'LAMBDA_FUNCTION_NAME'
    type: 'string'
    default: ''
  - name: 'LAMBDA_RUNTIME'
    type: 'string'
    default: 'provided.al2023'
  - name: 'LAMBDA_HANDLER'
    type: 'string'
    default: 'bootstrap'
  - name: 'LAMBDA_TIMEOUT'
    type: 'string'
    default: '30'
  - name: 'LAMBDA_MEMORY_SIZE'
    type: 'string'
    default: '128'
  - name: 'LAMBDA_ENV_VARS'
    type: 'string'
    default: ''
  - name: 'CREATE_IF_MISSING'
    type: 'boolean'
    default: false
  - name: 'SAM_CONFIG_ENV'
    type: 'string'
    default: 'default'

stages:
  - stage: 'deployment'
    displayName: 'deployment'
    condition: and(not(failed()), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    jobs:
      - job: 'deployment'
        displayName: 'deployment'
        container: 'ghcr.io/rios0rios0/pipelines/golang:1.25-awscli'
        steps:
          - task: 'DownloadPipelineArtifact@2'
            inputs:
              artifact: 'lambda-function-zip'
              path: "$(Build.SourcesDirectory)"
            displayName: 'Download Lambda ZIP Artifact'
            condition: eq(variables['DEPLOY_STRATEGY'], 'zip')

          - task: 'DownloadPipelineArtifact@2'
            inputs:
              artifact: 'lambda-sam-template'
              path: "$(Build.SourcesDirectory)"
            displayName: 'Download SAM Template Artifact'
            condition: eq(variables['DEPLOY_STRATEGY'], 'sam')

          # ZIP Deployment Strategy
          - task: 'AWSShellScript@1'
            displayName: 'Deploy Lambda Function via ZIP (AWS Service Connection)'
            condition: and(eq(variables['DEPLOY_STRATEGY'], 'zip'), ne(variables['AWS_SERVICE_CONNECTION'], ''))
            inputs:
                  awsCredentials: "$(AWS_SERVICE_CONNECTION)"
                  regionName: "$(AWS_REGION)"
                  scriptType: 'inline'
                  inlineScript: |
                    set -e

                    # Validate LAMBDA_FUNCTION_NAME is provided for ZIP deployment
                    if [ -z "${{ parameters.LAMBDA_FUNCTION_NAME }}" ]; then
                      echo "ERROR: LAMBDA_FUNCTION_NAME is required for ZIP deployment"
                      exit 1
                    fi

                    echo "Deploying Lambda function via AWS CLI..."

                    # Check if function exists
                    if aws lambda get-function --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} --region $(AWS_REGION) 2>/dev/null; then
                      echo "Updating existing Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"
                      aws lambda update-function-code \
                        --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                        --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                        --region $(AWS_REGION)

                      # Update configuration if environment variables are provided
                      if [ -n "${{ parameters.LAMBDA_ENV_VARS }}" ]; then
                        aws lambda update-function-configuration \
                          --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                          --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                          --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                          --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                          --region $(AWS_REGION)
                      else
                        aws lambda update-function-configuration \
                          --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                          --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                          --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                          --region $(AWS_REGION)
                      fi
                    else
                      # Only create if CREATE_IF_MISSING is true
                      if [ "${{ parameters.CREATE_IF_MISSING }}" = "true" ]; then
                        echo "Creating new Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"

                        # Note: Creating a Lambda function requires IAM role ARN
                        # This should be provided via environment variables or parameters
                        if [ -z "$LAMBDA_ROLE_ARN" ]; then
                          echo "ERROR: LAMBDA_ROLE_ARN environment variable is required to create a new Lambda function"
                          exit 1
                        fi

                        if [ -n "${{ parameters.LAMBDA_ENV_VARS }}" ]; then
                          aws lambda create-function \
                            --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                            --runtime ${{ parameters.LAMBDA_RUNTIME }} \
                            --handler ${{ parameters.LAMBDA_HANDLER }} \
                            --role "$LAMBDA_ROLE_ARN" \
                            --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                            --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                            --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                            --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                            --region $(AWS_REGION)
                        else
                          aws lambda create-function \
                            --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                            --runtime ${{ parameters.LAMBDA_RUNTIME }} \
                            --handler ${{ parameters.LAMBDA_HANDLER }} \
                            --role "$LAMBDA_ROLE_ARN" \
                            --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                            --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                            --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                            --region $(AWS_REGION)
                        fi
                      else
                        echo "ERROR: Lambda function ${{ parameters.LAMBDA_FUNCTION_NAME }} does not exist and CREATE_IF_MISSING is false"
                        exit 1
                      fi
                    fi

                    echo "Lambda function deployed successfully"

          - script: |
              set -e

              # Validate AWS credentials are set via environment variables
              if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
                echo "ERROR: AWS credentials not found. Please configure AWS_SERVICE_CONNECTION or set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
                exit 1
              fi

              # Validate LAMBDA_FUNCTION_NAME is provided for ZIP deployment
              if [ -z "${{ parameters.LAMBDA_FUNCTION_NAME }}" ]; then
                echo "ERROR: LAMBDA_FUNCTION_NAME is required for ZIP deployment"
                exit 1
              fi

              echo "Deploying Lambda function via AWS CLI..."

              # Check if function exists
              if aws lambda get-function --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} --region $(AWS_REGION) 2>/dev/null; then
                echo "Updating existing Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"
                aws lambda update-function-code \
                  --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                  --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                  --region $(AWS_REGION)

                # Update configuration if parameters are provided
                # Update configuration if environment variables are provided
                if [ -n "${{ parameters.LAMBDA_ENV_VARS }}" ]; then
                  aws lambda update-function-configuration \
                    --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                    --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                    --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                    --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                    --region $(AWS_REGION)
                else
                  aws lambda update-function-configuration \
                    --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                    --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                    --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                    --region $(AWS_REGION)
                fi
              else
                # If function does not exist, check if we should create it
                if [ "${{ parameters.CREATE_IF_MISSING }}" = "true" ]; then
                  echo "Creating new Lambda function: ${{ parameters.LAMBDA_FUNCTION_NAME }}"

                  # Note: Creating a Lambda function requires IAM role ARN
                  # This should be provided via environment variables or parameters
                  if [ -z "$LAMBDA_ROLE_ARN" ]; then
                    echo "ERROR: LAMBDA_ROLE_ARN environment variable is required to create a new Lambda function"
                    exit 1
                  fi  

                  if [ -n "${{ parameters.LAMBDA_ENV_VARS }}" ]; then
                    aws lambda create-function \
                      --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                      --runtime ${{ parameters.LAMBDA_RUNTIME }} \
                      --handler ${{ parameters.LAMBDA_HANDLER }} \
                      --role "$LAMBDA_ROLE_ARN" \
                      --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                      --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                      --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                      --environment "Variables={${{ parameters.LAMBDA_ENV_VARS }}}" \
                      --region $(AWS_REGION)
                  else
                    aws lambda create-function \
                      --function-name ${{ parameters.LAMBDA_FUNCTION_NAME }} \
                      --runtime ${{ parameters.LAMBDA_RUNTIME }} \
                      --handler ${{ parameters.LAMBDA_HANDLER }} \
                      --role "$LAMBDA_ROLE_ARN" \
                      --zip-file fileb://$(Build.SourcesDirectory)/lambda-function.zip \
                      --timeout ${{ parameters.LAMBDA_TIMEOUT }} \
                      --memory-size ${{ parameters.LAMBDA_MEMORY_SIZE }} \
                      --region $(AWS_REGION)
                  fi
                else
                  echo "ERROR: Lambda function ${{ parameters.LAMBDA_FUNCTION_NAME }} does not exist and CREATE_IF_MISSING is false"
                  exit 1
                fi
              echo "Lambda function deployed successfully"
            displayName: 'Deploy Lambda Function via ZIP (Environment Variables)'
            condition: and(eq(variables['DEPLOY_STRATEGY'], 'zip'), eq(variables['AWS_SERVICE_CONNECTION'], ''))

          # SAM Deployment Strategy
          - task: 'AWSShellScript@1'
            displayName: 'Deploy Lambda Function via SAM (AWS Service Connection)'
            condition: and(eq(variables['DEPLOY_STRATEGY'], 'sam'), ne(variables['AWS_SERVICE_CONNECTION'], ''))
            inputs:
                  awsCredentials: "$(AWS_SERVICE_CONNECTION)"
                  regionName: "$(AWS_REGION)"
                  scriptType: 'inline'
                  inlineScript: |
                    set -e

                    echo "Deploying Lambda function via AWS SAM..."

                    # Build sam deploy command
                    SAM_DEPLOY_CMD="sam deploy \
                      --template-file $(Build.SourcesDirectory)/packaged.yaml \
                      --config-env ${{ parameters.SAM_CONFIG_ENV }} \
                      --stack-name $(STACK_NAME) \
                      --no-confirm-changeset \
                      --region $(AWS_REGION)"

                    # Add parameter overrides if they exist
                    if [ -n "$(PARAMETER_OVERRIDES)" ]; then
                      SAM_DEPLOY_CMD="$SAM_DEPLOY_CMD --parameter-overrides $(PARAMETER_OVERRIDES)"
                    fi

                    eval $SAM_DEPLOY_CMD

          - script: |
              set -e

              # Validate AWS credentials are set via environment variables
              if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
                echo "ERROR: AWS credentials not found. Please configure AWS_SERVICE_CONNECTION or set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
                exit 1
              fi

              echo "Deploying Lambda function via AWS SAM..."

              # Build sam deploy command
              SAM_DEPLOY_CMD="sam deploy \
                --template-file $(Build.SourcesDirectory)/packaged.yaml \
                --config-env ${{ parameters.SAM_CONFIG_ENV }} \
                --stack-name $(STACK_NAME) \
                --no-confirm-changeset \
                --region $(AWS_REGION)"

              # Add parameter overrides if they exist
              if [ -n "$(PARAMETER_OVERRIDES)" ]; then
                SAM_DEPLOY_CMD="$SAM_DEPLOY_CMD --parameter-overrides $(PARAMETER_OVERRIDES)"
              fi

              eval $SAM_DEPLOY_CMD
            displayName: 'Deploy Lambda Function via SAM (Environment Variables)'
            condition: and(eq(variables['DEPLOY_STRATEGY'], 'sam'), eq(variables['AWS_SERVICE_CONNECTION'], ''))
