parameters:
  - name: 'RESOURCE_GROUP_NAME'
    type: 'string'
  - name: 'ENVIRONMENT'
    type: 'string'
  - name: 'AZM_SERVICE_CONNECTION'
    type: 'string'

steps:
  - task: 'AzureCLI@2'
    inputs:
      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -e

        mkdir -p $(AZURE_DEPLOY_CACHE)
        echo $AZURE_DEPLOY_OUTPUTS > $(AZURE_DEPLOY_CACHE)/outputs.json

        # Check if the file was created
        if [ -f "$(AZURE_DEPLOY_CACHE)/outputs.json" ]; then
          echo "$(date "+%Y-%m-%d %H:%M:%S") - File 'outputs.json' created with success!"
        else
          echo "$(date "+%Y-%m-%d %H:%M:%S") - Error: File 'outputs.json' file not found."
          exit 1
        fi
    displayName: 'Save Deployment Outputs to File'

  - task: 'AzureCLI@2'
    inputs:
      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -e

        outputs=$(cat $(AZURE_DEPLOY_CACHE)/outputs.json)
        echo "##vso[task.setvariable variable=OUTPUTS]$outputs"
    displayName: 'Read Outputs from file'
