parameters:
  - name: 'FILE'
    type: 'string'
  - name: 'DISPLAY_NAME'
    type: 'string'
    default: 'Replace Environment Variables'

steps:
  - script: |
      for var in $(compgen -e); do
        value=$(eval echo \$$var)
        escaped_value=$(printf '%s\n' "$value" | sed 's:[\/&]:\\&:g')
        sed -i "s/\${$var}/$escaped_value/g" ${{ parameters.FILE }}
      done
    displayName: "${{ parameters.DISPLAY_NAME }}"
