parameters:
  - name: 'SEMGREP_LANGUAGE'
    type: 'string'

jobs:
  - job: 'sast_horusec'
    displayName: 'sast:horusec'
    steps:
      - template: '../../abstracts/scripts-repo.yaml'
      - script: $(Scripts.Directory)/global/scripts/horusec/run.sh # TODO: needs to receive the requirements.txt
        continueOnError: true

      - task: 'PublishPipelineArtifact@1'
        inputs:
          artifactName: 'horusec'
          targetPath: 'build/reports'

  - job: 'sast_semgrep'
    displayName: 'sast:semgrep'
    steps:
      - template: '../../abstracts/scripts-repo.yaml'
      - script: $(Scripts.Directory)/global/scripts/semgrep/run.sh "${{ parameters.SEMGREP_LANGUAGE }}" # it takes the first param as the main language
        continueOnError: true

      - task: 'PublishPipelineArtifact@1'
        inputs:
          artifactName: 'semgrep'
          targetPath: 'build/reports'

  - job: 'sast_gitleaks'
    displayName: 'sast:gitleaks'
    steps:
      - checkout: 'self'
        fetchDepth: 0
        fetchTags: true

      - template: '../../abstracts/scripts-repo.yaml'
      - script: $(Scripts.Directory)/global/scripts/gitleaks/run.sh
        continueOnError: true

      - task: 'PublishPipelineArtifact@1'
        inputs:
          artifactName: 'gitleaks'
          targetPath: 'build/reports'
