jobs:
  - job: 'sast_trivy'
    displayName: 'sast:trivy'
    steps:
      - template: '../../abstracts/scripts-repo.yaml'
      - script: $(Scripts.Directory)/global/scripts/tools/trivy/run.sh
        continueOnError: true

      - task: 'PublishPipelineArtifact@1'
        inputs:
          artifactName: 'trivy'
          targetPath: 'build/reports/trivy'
