stages:
  - stage: 'tests'
    displayName: 'tests'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        variables:
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          - task: Docker@2
            displayName: Docker Login
            inputs:
              containerRegistry: '$(DOCKER_REGISTRY_SERVICE_CONNECTION)'
              command: login

          - template: '../../abstracts/test.yaml'

        continueOnError: false
