stages:
  - stage: 'tests'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'tests'
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        steps:
          - task: 'GoTool@0'
            inputs:
              version: '1.23.1'

          - template: '../../../global/abstracts/scripts-repo.yaml'

          # TODO: this should be a share script between the vendors
          - script: |
              set -e
              INIT_SCRIPT="config.sh"
              [[ -f $INIT_SCRIPT ]] && . ./$INIT_SCRIPT || echo "The '$INIT_SCRIPT' file is not found, skipping..."
            displayName: 'Load Custom Configuration'

          - script: $(Scripts.Directory)/global/scripts/golang/test/run.sh
            displayName: 'Run Tests'

          - task: 'PublishPipelineArtifact@1'
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/coverage.txt"
              artifact: 'coverage'
            displayName: 'Publish Coverage File'
        continueOnError: false
