parameters:
  - name: 'DEPENDS_ON'
    type: object
    default: ''

stages:
  - stage: 'tests'
    displayName: 'tests'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    ${{ if ne(parameters.DEPENDS_ON, '') }}:
      dependsOn: ${{ parameters.DEPENDS_ON }}
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        variables:
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          # $(Scripts.Directory) was already defined in the line below
          - template: '../../abstracts/test.yaml'

        continueOnError: false
