stages:
  - stage: 'tests'
    displayName: 'tests'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        variables:
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          # $(Scripts.Directory) was already defined in the line below
          - template: '../../abstracts/go1.23.4.yaml'

          - script: $(Scripts.Directory)/global/scripts/golang/test/run.sh
            displayName: 'Run Tests'

          - task: 'PublishTestResults@2'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
            displayName: 'Publish Test Results'

          - task: 'PublishCodeCoverageResults@2'
            inputs:
              summaryFileLocation: 'cobertura.xml'
            displayName: 'Publish Code Coverage Results'

          - task: 'PublishPipelineArtifact@1'
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/coverage.txt"
              artifact: 'coverage'
            displayName: 'Publish Coverage File'
        continueOnError: false
