stages:
  - stage: 'security'
    displayName: 'security (sca/sast)'
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: '../../../global/stages/20-security/docker.yaml'
        parameters:
          SEMGREP_LANGUAGE: 'golang'

      - template: '../../../global/stages/20-security/codeql.yaml'
        parameters:
          CODEQL_LANGUAGE: 'go'

      - template: '../../../global/stages/20-security/hadolint.yaml'

      - template: '../../../global/stages/20-security/trivy.yaml'

      - template: '../../../global/stages/20-security/trivy-sca.yaml'

      - job: 'sca_govulncheck'
        displayName: 'sca:govulncheck'
        variables:
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          - template: '../../abstracts/go.yaml'
          - script: |
              go install golang.org/x/vuln/cmd/govulncheck@latest
              "$(go env GOPATH)/bin/govulncheck" ./...
            displayName: 'Run govulncheck'
        continueOnError: true

      - job: 'sast_deadcode'
        displayName: 'sast:deadcode'
        variables:
          GOPATH: "$(Pipeline.Workspace)/.go"
        steps:
          - template: '../../abstracts/go.yaml'
          - script: |
              go install golang.org/x/tools/cmd/deadcode@latest
              "$(go env GOPATH)/bin/deadcode" -test ./...
            displayName: 'Run deadcode'
        continueOnError: true
