include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/golang/go-docker.yaml'

# Optional: Override variables
# variables:
#   SONAR_HOST_URL: 'https://sonar.example.com'

# Optional: Override the delivery stage for a custom Docker build
# .delivery:
#   script:
#     - docker build -t "$REGISTRY_PATH$IMAGE_SUFFIX:$TAG" -f Dockerfile .
#   cache:
#     key: 'test:all'
#     paths: !reference [ .go, cache, paths ]
#     policy: 'pull'
