# TODO: needs to be reviewed to use same configuration accross jobs via templates or other implementation
stages:
  - stage: 'code_check'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Code Check (Style/Quality)'
    jobs:
      - job: style_isort
        displayName: 'Check isort'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              python -m pip install pdm
              pdm install
              pdm run isort --check-only .
            displayName: 'Run isort check'
      - job: style_black
        displayName: 'Check black'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              python -m pip install pdm
              pdm install
              pdm run black --check .
            displayName: 'Run black check'

      - job: quality_flake8
        displayName: 'Check flake8'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              python -m pip install pdm
              pdm install
              pdm run flake8 .
            displayName: 'Run flake8 check'

      - job: quality_mypy
        displayName: 'Check mypy'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              python -m pip install pdm
              pdm install
              pdm run type-check 
            displayName: 'Run mypy check'
        continueOnError: true
