stages:
  - stage: 'code_check'
    displayName: 'code check (style/quality)'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: 'style_isort'
        displayName: 'style:isort'
        steps:
          - template: '../../abstracts/pdm-python3.11.yaml'
          - script: |
              pdm run isort --check-only .
            displayName: 'Run "isort" check'

      - job: 'style_black'
        displayName: 'style:black'
        steps:
          - template: '../../abstracts/pdm-python3.11.yaml'
          - script: |
              pdm run black --check .
            displayName: 'Run "black" check'

      - job: 'quality_flake8'
        displayName: 'quality:flake8'
        steps:
          - template: '../../abstracts/pdm-python3.11.yaml'
          - script: |
              pdm run flake8 .
            displayName: 'Run "flake8" check'

      - job: 'quality_mypy'
        displayName: 'quality:mypy'
        steps:
          - template: '../../abstracts/pdm-python3.11.yaml'
          - script: |
              pdm run type-check
            displayName: 'Run "mypy" check'
        continueOnError: true
