jobs:
  - job: 'release'
    displayName: 'release'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), or(contains(variables['Build.SourceVersionMessage'], 'origin/chore/bump-'), contains(variables['Build.SourceVersionMessage'], 'chore(bump)')))
    steps:
      - script: |
          set -eux
          COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
          REGEX="^Merge (remote-tracking|remote|tracking)? ?branch '(origin\/)?chore\/bump-([0-9]+\.[0-9]+\.[0-9]+)'.*$|.*chore\(bump\):.*version to ([0-9]+\.[0-9]+\.[0-9]+).*"

          if echo -n "$COMMIT_MESSAGE" | grep -Eq "$REGEX"; then
            VERSION=$(echo "$COMMIT_MESSAGE" | sed -En "s/$REGEX/\3\4/p" | head -n 1)

            RELEASE_NOTES=""
            if [ -f CHANGELOG.md ]; then
                RELEASE_NOTES=$(awk '/## \[Unreleased\]/ {skip=1; next} skip && /## \[.*\]/ {found=1; skip=0; next} found && /## \[.*\]/ {exit} found {print}' CHANGELOG.md)
                RELEASE_NOTES=$(echo "$RELEASE_NOTES" | jq --raw-input --slurp .)
            fi

            DATA="{
              \"name\": \"$VERSION\",
              \"taggedObject\": {
                \"objectId\": \"$(Build.SourceVersion)\"
              },
              \"message\": $RELEASE_NOTES
            }"

            curl -X POST "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/annotatedtags?api-version=7.1-preview.1" \
                 --header "Authorization: Bearer $(System.AccessToken)" \
                 --header "Content-Type: application/json" \
                 --data "$DATA"
          else
              echo 'Commit is not a bump, not creating a release'
          fi
