parameters:
  - name: 'TAG_PREFIXES'
    type: 'object'
    default:
      - ''

jobs:
  - job: 'release'
    displayName: 'release'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), or(contains(variables['Build.SourceVersionMessage'], 'origin/chore/bump-'), contains(variables['Build.SourceVersionMessage'], 'chore(bump)')))
    steps:
      - script: |
          set -eux

          COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
          REGEX="^Merge (remote-tracking|remote|tracking)? ?branch '(origin\/)?chore\/bump-([0-9]+\.[0-9]+\.[0-9]+)'.*$|.*chore\(bump\):.*version to ([0-9]+\.[0-9]+\.[0-9]+).*"

          if echo -n "$COMMIT_MESSAGE" | grep -Eq "$REGEX"; then
            VERSION=$(echo "$COMMIT_MESSAGE" | sed -En "s/$REGEX/\3\4/p" | head -n 1)
            echo "##vso[task.setvariable variable=RELEASE_VERSION]$VERSION"
          else
            echo "$(date "+%Y-%m-%d %H:%M:%S") - Commit is not a bump, not creating a release..."
            echo "##vso[task.setvariable variable=SKIP_RELEASE]true"
          fi
        displayName: 'Extract Release Version'

      - ${{ each prefix in parameters.TAG_PREFIXES }}:
        - script: |
            set -eux

            # only run if extraction found a version
            if [ "${SKIP_RELEASE:-}" = "true" ]; then
              echo "Skipping tag creation for prefix '${VERSION_PREFIX:-}' because no bump commit was detected."
              exit 0
            fi

            RELEASE_NOTES=""
            if [ -f CHANGELOG.md ]; then
                RELEASE_NOTES=$(awk '/## \[Unreleased\]/ {skip=1; next} skip && /## \[.*\]/ {found=1; skip=0; next} found && /## \[.*\]/ {exit} found {print}' CHANGELOG.md)
                RELEASE_NOTES=$(echo "$RELEASE_NOTES" | jq --raw-input --slurp .)
            fi

            DATA="{
              \"name\": \"${VERSION_PREFIX}${RELEASE_VERSION}\",
              \"taggedObject\": {
                \"objectId\": \"$(Build.SourceVersion)\"
              },
              \"message\": $RELEASE_NOTES
            }"

            curl -X POST "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/annotatedtags?api-version=7.1-preview.1" \
                 --header "Authorization: Bearer $(System.AccessToken)" \
                 --header "Content-Type: application/json" \
                 --data "$DATA"
          displayName: "Create Tag w/ Prefix '${{ prefix }}'"
          env:
            VERSION_PREFIX: "${{ prefix }}"
