inputs:
  binary_name:
    type: 'string'
    required: true
    description: 'Binary name to be used as default source'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v6'

    - run: |
        echo "PACKAGE_NAME=$(echo '${{ inputs.binary_name }}-${{ github.ref }}' | sed 's/refs\/tags\///')" >> $GITHUB_ENV
      shell: 'bash'

    - name: 'Build Binary'
      run: make build
      shell: 'bash'

    - name: 'Compress Binary'
      run: cd bin && zip -9 "$PACKAGE_NAME.zip" "${{ inputs.binary_name }}"
      shell: 'bash'

    - name: 'Upload Binary'
      uses: 'actions/upload-artifact@v6'
      with:
        name: '${{ inputs.binary_name }}'
        path: 'bin/${{ env.PACKAGE_NAME }}.zip'

    - name: 'Download Binary'
      uses: 'actions/download-artifact@v7'
      with:
        name: '${{ inputs.binary_name }}'

    - name: 'Upload to Release'
      uses: 'softprops/action-gh-release@v2'
      with:
        files: ${{ env.PACKAGE_NAME }}.zip
