on:
  workflow_call:

inputs:
  binary_name:
    type: 'string'
    description: 'Binary name to be used as default source'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v6'

    - run: |
        echo "PACKAGE_NAME=$(echo '${{ inputs.binary_name }}-${{ github.ref }}' | sed 's/refs\/tags\///')" >> $GITHUB_ENV
      shell: 'bash'

    - run: |
        make build
        strip -s bin/${{ inputs.binary_name }}
      shell: 'bash'

    - run: |
        cd bin
        zip -9 $PACKAGE_NAME.zip ${{ inputs.binary_name }}
      shell: 'bash'

    - name: 'Upload Binary'
      uses: 'actions/upload-artifact@v6'
      with:
        name: '${{ inputs.binary_name }}'
        path: 'bin/${{ env.PACKAGE_NAME }}.zip'

    - name: 'Download Binary'
      uses: 'actions/download-artifact@v7'
      with:
        name: '${{ inputs.binary_name }}'

    - name: 'Upload to Release'
      uses: 'actions/upload-release-asset@v1'
      with:
        upload_url: '${{ steps.create_release.outputs.upload_url }}'
        asset_path: '${{ env.PACKAGE_NAME }}.zip'
        asset_name: '${{ env.PACKAGE_NAME }}.zip'
        asset_content_type: 'application/zip'
