on:
  workflow_call:

jobs:
  composer:
    uses: 'rios0rios0/pipelines/.github/workflows/composer.yaml@main'

  # fourth stage
  delivery-release:
    name: 'delivery > release'
    runs-on: 'ubuntu-latest'
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: 'release'
        uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/release@main'
    needs: [ 'composer' ]
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'chore/bump-')"

  delivery-docker:
    name: 'delivery > docker'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/docker@main'
        with:
          tag_name: "${{ needs.delivery-release.outputs.tag_name }}"
    needs: [ 'composer', 'delivery-release' ]
    if: "!failure() && ((github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/'))"
