# see the bottom of the file for more information¹
# the parent workflow is responsible for setting up the call events²
on:
  workflow_call:

# it wasn't needed to set up anything for GoLang because 'ubuntu-latest' has all dependencies
jobs:
  # first stage
  code_check-style_golangci_lint:
    name: 'code-check > style:golangci-lint'
    runs-on: 'ubuntu-latest'
    steps:
      - run: sudo apt-get update && sudo apt-get install -y python3 python3-yaml
      - uses: 'rios0rios0/pipelines/github/golang/stages/10-code-check/golangci-lint@main'
    continue-on-error: true
    if: "!startsWith(github.ref, 'refs/tags/')"


  # second stage
  security-sast_horusec:
    name: 'security > sast:horusec'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/docker-horusec@main'
    needs: [ 'code_check-style_golangci_lint' ]
    continue-on-error: true # TODO: this is a temporary fix, remove it after the issue is fixed
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sast_semgrep:
    name: 'security > sast:semgrep'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/docker-semgrep@main'
        with:
          semgrep_lang: 'golang'
    needs: [ 'code_check-style_golangci_lint' ]
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sast_gitleaks:
    name: 'security > sast:gitleaks'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/docker-gitleaks@main'
    needs: [ 'code_check-style_golangci_lint' ]
    if: "!startsWith(github.ref, 'refs/tags/')"


  # third stage
  tests-test_all:
    name: 'tests > test:all'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/golang/stages/30-tests/all@main'
    needs: [ 'security-sast_horusec', 'security-sast_semgrep', 'security-sast_gitleaks' ]
    if: "!startsWith(github.ref, 'refs/tags/')"


  # fourth stage
  delivery-release:
    name: 'delivery > release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/release@main'
    needs: [ 'tests-test_all' ]
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'chore/bump-')"


# 1 - this file MUST be inside ".github/workflows" because of GitHub Actions limitations
# 2- the recommended events to trigger this workflow and permissions are:
#on:
#  push:
#    branches:
#      - 'main'
#    tags:
#      - '*'
#  pull_request:
#    branches:
#      - 'main'
#  workflow_dispatch:
#
#permissions:
#  checks: 'write' # code_check-style_golangci_lint
#  contents: 'write' # delivery-release
