# see the bottom of the file for more information¹
# the parent workflow is responsible for setting up the call events²
on:
  workflow_call:
    outputs:
      tag_name:
        description: 'The tag name created by the release job'
        value: ${{ jobs.delivery-release.outputs.tag_name }}

jobs:
  # first stage
  code_check-basic_checks:
    name: 'code-check > quality:basic-checks'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/10-code-check/basic-checks@main'
        with:
          target_branch: ${{ github.event.pull_request.base.ref || github.event.repository.default_branch || 'main' }}
    if: "github.event_name == 'pull_request'"

  code_check-style_eslint:
    name: 'code-check > style:eslint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v6'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20'
          cache: 'npm'

      - run: |
          npm ci
          npm run lint:ci
        shell: 'bash'
    continue-on-error: true
    if: "!startsWith(github.ref, 'refs/tags/')"


  # second stage
  security-sast_codeql:
    name: 'security > sast:codeql'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/codeql@main'
        with:
          codeql_language: 'javascript-typescript'
    needs: [ 'code_check-style_eslint' ]
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sast_semgrep:
    name: 'security > sast:semgrep'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/docker-semgrep@main'
        with:
          semgrep_lang: 'javascript'
    needs: [ 'code_check-style_eslint' ]
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sast_gitleaks:
    name: 'security > sast:gitleaks'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/docker-gitleaks@main'
    needs: [ 'code_check-style_eslint' ]
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sast_hadolint:
    name: 'security > sast:hadolint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/hadolint@main'
    needs: [ 'code_check-style_eslint' ]
    continue-on-error: true
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sast_trivy:
    name: 'security > sast:trivy'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/trivy@main'
    needs: [ 'code_check-style_eslint' ]
    continue-on-error: true
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sca_trivy:
    name: 'security > sca:trivy'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/20-security/trivy-sca@main'
    needs: [ 'code_check-style_eslint' ]
    continue-on-error: true
    if: "!startsWith(github.ref, 'refs/tags/')"

  security-sca_npm_audit:
    name: 'security > sca:npm-audit'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v6'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20'
          cache: 'npm'

      - run: |
          npm ci
          npm audit --audit-level=high
        shell: 'bash'
    needs: [ 'code_check-style_eslint' ]
    continue-on-error: true
    if: "!startsWith(github.ref, 'refs/tags/')"


  # third stage
  tests-test_all:
    name: 'tests > test:all'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v6'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20'
          cache: 'npm'

      - run: |
          npm ci
          npm run test:ci
        shell: 'bash'
    needs: [ 'security-sast_codeql', 'security-sast_semgrep', 'security-sast_gitleaks', 'security-sast_hadolint', 'security-sast_trivy', 'security-sca_trivy', 'security-sca_npm_audit' ]
    if: "!startsWith(github.ref, 'refs/tags/')"

  tests-test_build:
    name: 'tests > test:build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v6'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20'
          cache: 'npm'

      - run: |
          npm ci
          npm run build
        shell: 'bash'
    needs: [ 'security-sast_codeql', 'security-sast_semgrep', 'security-sast_gitleaks', 'security-sast_hadolint', 'security-sast_trivy', 'security-sca_trivy', 'security-sca_npm_audit' ]
    if: "!startsWith(github.ref, 'refs/tags/')"


  # fourth stage
  delivery-release:
    name: 'delivery > release'
    runs-on: 'ubuntu-latest'
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: 'release'
        uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/release@main'
    needs: [ 'tests-test_all', 'tests-test_build' ]
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && (contains(github.event.head_commit.message, 'chore/bump-') || contains(github.event.head_commit.message, 'bump/') || contains(github.event.head_commit.message, 'chore(bump)'))"


# 1 - this file MUST be inside ".github/workflows" because of GitHub Actions limitations
# 2 - the recommended events to trigger this workflow and permissions are:
#   on:
#     push:
#       branches:
#         - 'main'
#       tags:
#         - '*'
#     pull_request:
#       branches:
#         - 'main'
#     workflow_dispatch:
#
#   permissions:
#     security-events: 'write' # security-sast_codeql
#     contents: 'write' # delivery-release
