stages:
  - stage: 'delivery'
    displayName: 'delivery'
    condition: and(not(failed()), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        variables:
          MIGRATIONS_CACHE: "$(Build.SourcesDirectory)/.migration"
          GOPATH: "$(Pipeline.Workspace)/.go"
          SEEDERS_CACHE: "$(Build.SourcesDirectory)/.seeder"
          AZURE_DEPLOY_CACHE: "$(Build.SourcesDirectory)/.azuredeploy"
        steps:
          - template: '../../abstracts/arm.yaml'

          - task: 'CopyFiles@2'
            inputs:
              Contents: |
                azuredeploy.json
              TargetFolder: "$(Build.SourcesDirectory)/build/templates"
            displayName: 'Copy azuredeploy.json'

          - task: 'PublishPipelineArtifact@1'
            inputs:
              artifactName: 'AzureDeployFile'
              targetPath: "$(Build.SourcesDirectory)/build/templates/azuredeploy.json"
            displayName: 'Publish azuredeploy.json Artifact'

          - task: 'PublishPipelineArtifact@1'
            inputs:
              artifactName: 'BuildArtifact'
              targetPath: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
            displayName: 'Publish ZIP Artifact'

      - template: '../../../global/stages/40-delivery/release.yaml'
