stages:
  - stage: 'delivery'
    displayName: 'delivery'
    condition: and(not(failed()), or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    jobs:
      - job: 'delivery'
        displayName: 'delivery'
        variables:
          MIGRATIONS_CACHE: "$(Build.SourcesDirectory)/.migration"
          GOPATH: "$(Pipeline.Workspace)/.go"
          SEEDERS_CACHE: "$(Build.SourcesDirectory)/.seeder"
          AZURE_DEPLOY_CACHE: "$(Build.SourcesDirectory)/.azuredeploy"
          PIPELINE_FIREWALL_NAME: 'PipelineFirewall_$(date +"%Y%m%d%H%M%S")'
        steps:
          - template: '../../abstracts/arm.yaml'

      - template: '../../../global/stages/40-delivery/release.yaml'
